#!/usr/bin/env python3
"""Offline generator for the R=1024 B_cred credit-threshold table (PROMPT
BINDING.md §4).

The consensus B_cred score credits, per decode step, an integer number of
"credit units" (R units == 1 bit) equal to::

    credit_units(mass_q) = max { n in [0, 32*R] : mass_q <= threshold_q63[n] }

where ``mass_q`` is the step's conservative interval mass in Q63 fixed point
(0 .. 2^63) and::

    threshold_q63[n] = floor( 2^63 * 2^(-n/R) )     for n = 0 .. 32*R

This script computes that table ONCE, offline, with high-precision decimal
arithmetic (never runtime pow/exp/log), verifies each value is a stable floor,
and emits three checked-in artifacts that MUST stay byte-consistent:

  * ``bcred_table_r1024.bin``  — canonical little-endian uint64 payload; its
    SHA-256 is the table identity that both languages assert at load time.
  * ``bcred_table_r1024.py``   — the Python table module (base64 of the same
    bytes, decoded + hash-checked at import).
  * ``bcred_table_r1024.cpp`` / ``.h`` — the C++ table (integer literals, same
    values; a startup self-check re-hashes the little-endian encoding).

Regenerate with::

    python3 gen_bcred_table.py

and re-run the cross-language vector tests; the printed SHA-256 must match the
constant embedded in both emitted files (the script writes them, so it does).
"""

import base64
import hashlib
import struct
from decimal import Decimal, getcontext, ROUND_FLOOR

# --------------------------------------------------------------------------- #
# Table parameters — MUST match pow_v3.BCRED_R / pow_v3.h BCRED_R.
# --------------------------------------------------------------------------- #
R = 1024                       # credit units per bit
N_MAX = 32 * R                 # 32 bits * R  == 32768  (per-step cap index)
TABLE_LEN = N_MAX + 1          # n = 0 .. N_MAX inclusive  == 32769
Q_ONE = 1 << 63                # Q63 unit (mass == 1.0)

# Two precisions: the working precision and a strictly higher cross-check
# precision. floor() must be identical at both, else the value sits too close
# to an integer boundary for the working precision and we must raise.
PREC_WORK = 60
PREC_CHECK = 120


def _floor_threshold(n: int, prec: int) -> int:
    """floor(2^63 * 2^(-n/R)) computed with `prec` significant decimal digits."""
    getcontext().prec = prec
    # 2^(-n/R): division is exact-to-prec, power is correctly-rounded exp/ln.
    factor = Decimal(2) ** (Decimal(-n) / Decimal(R))
    val = Decimal(Q_ONE) * factor
    return int(val.to_integral_value(rounding=ROUND_FLOOR))


def build_table() -> list:
    table = []
    prev = None
    for n in range(TABLE_LEN):
        v = _floor_threshold(n, PREC_WORK)
        # Stability: the floor must not change at a strictly higher precision.
        v_hi = _floor_threshold(n, PREC_CHECK)
        if v != v_hi:
            raise SystemExit(
                f"UNSTABLE floor at n={n}: prec{PREC_WORK}={v} "
                f"prec{PREC_CHECK}={v_hi} — raise PREC_WORK")
        # Range + monotonicity invariants.
        if not (0 <= v <= Q_ONE):
            raise SystemExit(f"threshold out of range at n={n}: {v}")
        if prev is not None and v > prev:
            raise SystemExit(
                f"non-monotone table at n={n}: {v} > prev {prev}")
        prev = v
        table.append(v)
    # Exact anchors: 2^0 -> 2^63, 2^-32 -> 2^31.
    if table[0] != Q_ONE:
        raise SystemExit(f"threshold[0] must be 2^63, got {table[0]}")
    if table[N_MAX] != (1 << 31):
        raise SystemExit(f"threshold[N_MAX] must be 2^31, got {table[N_MAX]}")
    return table


def pack_le(table: list) -> bytes:
    return struct.pack("<%dQ" % len(table), *table)


PY_TEMPLATE = '''\
# @generated by gen_bcred_table.py — DO NOT EDIT BY HAND.
#
# R=1024 B_cred credit-threshold table (TIP-0003). This module is
# the sibling of pow_v3.py; it is imported there. `THRESHOLDS_Q63[n]` is
# floor(2^63 * 2^(-n/R)) for n = 0 .. 32*R. The payload is the base64 of the
# little-endian uint64 encoding; its SHA-256 (BCRED_TABLE_SHA256) is the
# consensus table identity, re-verified at import in both languages.
import base64 as _b64
import hashlib as _hashlib
import struct as _struct

BCRED_R = {R}
BCRED_N_MAX = {N_MAX}
BCRED_TABLE_LEN = {TABLE_LEN}
BCRED_TABLE_SHA256 = "{sha}"

_PAYLOAD_B64 = (
{payload_lines}
)

_raw = _b64.b64decode(_PAYLOAD_B64)
if _hashlib.sha256(_raw).hexdigest() != BCRED_TABLE_SHA256:
    raise RuntimeError("bcred_table_r1024: payload SHA-256 mismatch (corrupt table)")
if len(_raw) != BCRED_TABLE_LEN * 8:
    raise RuntimeError("bcred_table_r1024: unexpected payload length")

THRESHOLDS_Q63 = _struct.unpack("<%dQ" % BCRED_TABLE_LEN, _raw)

# Cheap load-time invariants (defence-in-depth; the SHA already pins bytes).
assert THRESHOLDS_Q63[0] == (1 << 63)
assert THRESHOLDS_Q63[BCRED_N_MAX] == (1 << 31)
'''


def emit_python(path: str, table: list, sha: str, b64_payload: str) -> None:
    # Wrap the base64 to 76-char lines inside a parenthesised implicit-concat.
    lines = []
    for i in range(0, len(b64_payload), 76):
        lines.append('    "%s"' % b64_payload[i:i + 76])
    payload_lines = "\n".join(lines)
    src = PY_TEMPLATE.format(
        R=R, N_MAX=N_MAX, TABLE_LEN=TABLE_LEN, sha=sha,
        payload_lines=payload_lines)
    with open(path, "w") as f:
        f.write(src)


H_TEMPLATE = '''\
// @generated by gen_bcred_table.py — DO NOT EDIT BY HAND.
//
// R=1024 B_cred credit-threshold table (TIP-0003).
// BCRED_THRESHOLD_Q63[n] == floor(2^63 * 2^(-n/R)) for n = 0 .. 32*R.
#ifndef POW_V3_BCRED_TABLE_R1024_H
#define POW_V3_BCRED_TABLE_R1024_H

#include <cstdint>
#include <cstddef>

namespace pow_v3 {{

constexpr std::size_t BCRED_R = {R};
constexpr std::size_t BCRED_N_MAX = {N_MAX};
constexpr std::size_t BCRED_TABLE_LEN = {TABLE_LEN};

// SHA-256 of the little-endian uint64 encoding of BCRED_THRESHOLD_Q63 — the
// consensus table identity, identical to bcred_table_r1024.py's constant. The
// cross-language vector test re-hashes the compiled array and asserts it
// equals this string (and equals the Python table's SHA).
extern const char* const BCRED_TABLE_SHA256_HEX;

extern const uint64_t BCRED_THRESHOLD_Q63[BCRED_TABLE_LEN];

}}  // namespace pow_v3

#endif  // POW_V3_BCRED_TABLE_R1024_H
'''


CPP_TEMPLATE = '''\
// @generated by gen_bcred_table.py — DO NOT EDIT BY HAND.
//
// R=1024 B_cred credit-threshold table (TIP-0003). Integer values
// identical to bcred_table_r1024.py THRESHOLDS_Q63; see gen_bcred_table.py.
#include "bcred_table_r1024.h"

#include <cstdint>

namespace pow_v3 {{

const char* const BCRED_TABLE_SHA256_HEX =
    "{sha}";

const uint64_t BCRED_THRESHOLD_Q63[BCRED_TABLE_LEN] = {{
{entries}
}};

}}  // namespace pow_v3
'''


def emit_cpp(cpp_path: str, h_path: str, table: list, sha: str) -> None:
    with open(h_path, "w") as f:
        f.write(H_TEMPLATE.format(R=R, N_MAX=N_MAX, TABLE_LEN=TABLE_LEN))
    # 6 hex literals per line to keep the file navigable.
    chunk = []
    per_line = 6
    lines = []
    for i, v in enumerate(table):
        chunk.append("0x%016xULL" % v)
        if len(chunk) == per_line:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk) + ",")
    entries = "\n".join(lines)
    with open(cpp_path, "w") as f:
        f.write(CPP_TEMPLATE.format(sha=sha, entries=entries))


def main() -> None:
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    table = build_table()
    raw = pack_le(table)
    sha = hashlib.sha256(raw).hexdigest()
    b64_payload = base64.b64encode(raw).decode("ascii")

    with open(os.path.join(here, "bcred_table_r1024.bin"), "wb") as f:
        f.write(raw)
    emit_python(os.path.join(here, "bcred_table_r1024.py"), table, sha, b64_payload)
    emit_cpp(os.path.join(here, "bcred_table_r1024.cpp"),
             os.path.join(here, "bcred_table_r1024.h"), table, sha)

    print("R                 =", R)
    print("N_MAX (== 32*R)   =", N_MAX)
    print("TABLE_LEN         =", TABLE_LEN)
    print("bytes             =", len(raw))
    print("threshold[0]      =", table[0], "(== 2^63:", table[0] == Q_ONE, ")")
    print("threshold[R]      =", table[R], "(1 bit  boundary)")
    print("threshold[N_MAX]  =", table[N_MAX], "(== 2^31:", table[N_MAX] == (1 << 31), ")")
    print("SHA256            =", sha)


if __name__ == "__main__":
    main()
