# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BlockHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BlockHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBlockHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BlockHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BlockHeader
    def ReqId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockHeader
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockHeader
    def PrevBlockHash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BlockHeader
    def PrevBlockHashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BlockHeader
    def PrevBlockHashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BlockHeader
    def PrevBlockHashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # BlockHeader
    def MerkleRoot(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BlockHeader
    def MerkleRootAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BlockHeader
    def MerkleRootLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BlockHeader
    def MerkleRootIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # BlockHeader
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockHeader
    def Bits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BlockHeaderStart(builder):
    builder.StartObject(6)

def Start(builder):
    BlockHeaderStart(builder)

def BlockHeaderAddReqId(builder, reqId):
    builder.PrependUint32Slot(0, reqId, 0)

def AddReqId(builder, reqId):
    BlockHeaderAddReqId(builder, reqId)

def BlockHeaderAddVersion(builder, version):
    builder.PrependUint32Slot(1, version, 0)

def AddVersion(builder, version):
    BlockHeaderAddVersion(builder, version)

def BlockHeaderAddPrevBlockHash(builder, prevBlockHash):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(prevBlockHash), 0)

def AddPrevBlockHash(builder, prevBlockHash):
    BlockHeaderAddPrevBlockHash(builder, prevBlockHash)

def BlockHeaderStartPrevBlockHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPrevBlockHashVector(builder, numElems):
    return BlockHeaderStartPrevBlockHashVector(builder, numElems)

def BlockHeaderAddMerkleRoot(builder, merkleRoot):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(merkleRoot), 0)

def AddMerkleRoot(builder, merkleRoot):
    BlockHeaderAddMerkleRoot(builder, merkleRoot)

def BlockHeaderStartMerkleRootVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartMerkleRootVector(builder, numElems):
    return BlockHeaderStartMerkleRootVector(builder, numElems)

def BlockHeaderAddTimestamp(builder, timestamp):
    builder.PrependUint32Slot(4, timestamp, 0)

def AddTimestamp(builder, timestamp):
    BlockHeaderAddTimestamp(builder, timestamp)

def BlockHeaderAddBits(builder, bits):
    builder.PrependUint32Slot(5, bits, 0)

def AddBits(builder, bits):
    BlockHeaderAddBits(builder, bits)

def BlockHeaderEnd(builder):
    return builder.EndObject()

def End(builder):
    return BlockHeaderEnd(builder)
