# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BlockValidation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BlockValidation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBlockValidation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BlockValidation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BlockValidation
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockValidation
    def Hash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BlockValidation
    def HashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BlockValidation
    def HashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BlockValidation
    def HashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # BlockValidation
    def PrevBlockHash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BlockValidation
    def PrevBlockHashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BlockValidation
    def PrevBlockHashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BlockValidation
    def PrevBlockHashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # BlockValidation
    def MerkleRoot(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BlockValidation
    def MerkleRootAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BlockValidation
    def MerkleRootLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BlockValidation
    def MerkleRootIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # BlockValidation
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockValidation
    def Bits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockValidation
    def Nonce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockValidation
    def PowBlobHash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BlockValidation
    def PowBlobHashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BlockValidation
    def PowBlobHashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BlockValidation
    def PowBlobHashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # BlockValidation
    def AdjustedBits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlockValidation
    def PowBlob(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from proof.Proof import Proof
            obj = Proof()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BlockValidation
    def Difficulty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def BlockValidationStart(builder):
    builder.StartObject(11)

def Start(builder):
    BlockValidationStart(builder)

def BlockValidationAddVersion(builder, version):
    builder.PrependUint32Slot(0, version, 0)

def AddVersion(builder, version):
    BlockValidationAddVersion(builder, version)

def BlockValidationAddHash(builder, hash):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(hash), 0)

def AddHash(builder, hash):
    BlockValidationAddHash(builder, hash)

def BlockValidationStartHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartHashVector(builder, numElems):
    return BlockValidationStartHashVector(builder, numElems)

def BlockValidationAddPrevBlockHash(builder, prevBlockHash):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(prevBlockHash), 0)

def AddPrevBlockHash(builder, prevBlockHash):
    BlockValidationAddPrevBlockHash(builder, prevBlockHash)

def BlockValidationStartPrevBlockHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPrevBlockHashVector(builder, numElems):
    return BlockValidationStartPrevBlockHashVector(builder, numElems)

def BlockValidationAddMerkleRoot(builder, merkleRoot):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(merkleRoot), 0)

def AddMerkleRoot(builder, merkleRoot):
    BlockValidationAddMerkleRoot(builder, merkleRoot)

def BlockValidationStartMerkleRootVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartMerkleRootVector(builder, numElems):
    return BlockValidationStartMerkleRootVector(builder, numElems)

def BlockValidationAddTimestamp(builder, timestamp):
    builder.PrependUint32Slot(4, timestamp, 0)

def AddTimestamp(builder, timestamp):
    BlockValidationAddTimestamp(builder, timestamp)

def BlockValidationAddBits(builder, bits):
    builder.PrependUint32Slot(5, bits, 0)

def AddBits(builder, bits):
    BlockValidationAddBits(builder, bits)

def BlockValidationAddNonce(builder, nonce):
    builder.PrependUint32Slot(6, nonce, 0)

def AddNonce(builder, nonce):
    BlockValidationAddNonce(builder, nonce)

def BlockValidationAddPowBlobHash(builder, powBlobHash):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(powBlobHash), 0)

def AddPowBlobHash(builder, powBlobHash):
    BlockValidationAddPowBlobHash(builder, powBlobHash)

def BlockValidationStartPowBlobHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPowBlobHashVector(builder, numElems):
    return BlockValidationStartPowBlobHashVector(builder, numElems)

def BlockValidationAddAdjustedBits(builder, adjustedBits):
    builder.PrependUint32Slot(8, adjustedBits, 0)

def AddAdjustedBits(builder, adjustedBits):
    BlockValidationAddAdjustedBits(builder, adjustedBits)

def BlockValidationAddPowBlob(builder, powBlob):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(powBlob), 0)

def AddPowBlob(builder, powBlob):
    BlockValidationAddPowBlob(builder, powBlob)

def BlockValidationAddDifficulty(builder, difficulty):
    builder.PrependInt64Slot(10, difficulty, 0)

def AddDifficulty(builder, difficulty):
    BlockValidationAddDifficulty(builder, difficulty)

def BlockValidationEnd(builder):
    return builder.EndObject()

def End(builder):
    return BlockValidationEnd(builder)
