# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ModelValidation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelValidation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelValidation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelValidation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelValidation
    def ModelName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelValidation
    def ModelCommit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelValidation
    def Difficulty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelValidation
    def Cid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelValidation
    def Extra(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelValidation
    def Txid(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ModelValidation
    def TxidAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ModelValidation
    def TxidLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelValidation
    def TxidIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ModelValidation
    def BlockHash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ModelValidation
    def BlockHashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ModelValidation
    def BlockHashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ModelValidation
    def BlockHashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ModelValidation
    def BlockHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ModelValidationStart(builder):
    builder.StartObject(8)

def Start(builder):
    ModelValidationStart(builder)

def ModelValidationAddModelName(builder, modelName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(modelName), 0)

def AddModelName(builder, modelName):
    ModelValidationAddModelName(builder, modelName)

def ModelValidationAddModelCommit(builder, modelCommit):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(modelCommit), 0)

def AddModelCommit(builder, modelCommit):
    ModelValidationAddModelCommit(builder, modelCommit)

def ModelValidationAddDifficulty(builder, difficulty):
    builder.PrependInt64Slot(2, difficulty, 0)

def AddDifficulty(builder, difficulty):
    ModelValidationAddDifficulty(builder, difficulty)

def ModelValidationAddCid(builder, cid):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(cid), 0)

def AddCid(builder, cid):
    ModelValidationAddCid(builder, cid)

def ModelValidationAddExtra(builder, extra):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(extra), 0)

def AddExtra(builder, extra):
    ModelValidationAddExtra(builder, extra)

def ModelValidationAddTxid(builder, txid):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(txid), 0)

def AddTxid(builder, txid):
    ModelValidationAddTxid(builder, txid)

def ModelValidationStartTxidVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartTxidVector(builder, numElems):
    return ModelValidationStartTxidVector(builder, numElems)

def ModelValidationAddBlockHash(builder, blockHash):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(blockHash), 0)

def AddBlockHash(builder, blockHash):
    ModelValidationAddBlockHash(builder, blockHash)

def ModelValidationStartBlockHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartBlockHashVector(builder, numElems):
    return ModelValidationStartBlockHashVector(builder, numElems)

def ModelValidationAddBlockHeight(builder, blockHeight):
    builder.PrependInt32Slot(7, blockHeight, 0)

def AddBlockHeight(builder, blockHeight):
    ModelValidationAddBlockHeight(builder, blockHeight)

def ModelValidationEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelValidationEnd(builder)
