# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

class ResponseValue(object):
    Quick_OK = 0
    Quick_Fail = 1
    Quick_OK_Smell_OK = 2
    Quick_OK_Smell_Fail = 3
    Quick_Fail_Smell_OK = 4
    Quick_Fail_Smell_Fail = 5
    Full_Green = 6
    Full_Amber = 7
    Full_Red = 8
    Model_OK = 9
    Model_Fail = 10
    Challenge_OK = 11
    Challenge_Fail = 12
    Model_Pending_Review = 13
    Logits_OK = 14
    Logits_Fail = 15
