# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ValidationResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ValidationResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsValidationResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ValidationResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ValidationResponse
    def HashIdentifier(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ValidationResponse
    def HashIdentifierAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ValidationResponse
    def HashIdentifierLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ValidationResponse
    def HashIdentifierIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ValidationResponse
    def EnumResponse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ValidationResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    ValidationResponseStart(builder)

def ValidationResponseAddHashIdentifier(builder, hashIdentifier):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hashIdentifier), 0)

def AddHashIdentifier(builder, hashIdentifier):
    ValidationResponseAddHashIdentifier(builder, hashIdentifier)

def ValidationResponseStartHashIdentifierVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartHashIdentifierVector(builder, numElems):
    return ValidationResponseStartHashIdentifierVector(builder, numElems)

def ValidationResponseAddEnumResponse(builder, enumResponse):
    builder.PrependUint8Slot(1, enumResponse, 0)

def AddEnumResponse(builder, enumResponse):
    ValidationResponseAddEnumResponse(builder, enumResponse)

def ValidationResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ValidationResponseEnd(builder)
