# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

class ValidationType(object):
    Quick = 0
    Quick_Smell = 1
    Full = 2
    Model = 3
    Challenge = 4
    Logits = 5
