# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

class ValidationUnion(object):
    NONE = 0
    BlockValidation = 1
    ModelValidation = 2
