# SPDX-License-Identifier: Apache-2.0
# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ValidationRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ValidationRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsValidationRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ValidationRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ValidationRequest
    def HashId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ValidationRequest
    def HashIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ValidationRequest
    def HashIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ValidationRequest
    def HashIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ValidationRequest
    def ValidationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ValidationRequest
    def RequestType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ValidationRequest
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ValidationRequestStart(builder):
    builder.StartObject(4)

def Start(builder):
    ValidationRequestStart(builder)

def ValidationRequestAddHashId(builder, hashId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hashId), 0)

def AddHashId(builder, hashId):
    ValidationRequestAddHashId(builder, hashId)

def ValidationRequestStartHashIdVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartHashIdVector(builder, numElems):
    return ValidationRequestStartHashIdVector(builder, numElems)

def ValidationRequestAddValidationType(builder, validationType):
    builder.PrependUint8Slot(1, validationType, 0)

def AddValidationType(builder, validationType):
    ValidationRequestAddValidationType(builder, validationType)

def ValidationRequestAddRequestType(builder, requestType):
    builder.PrependUint8Slot(2, requestType, 0)

def AddRequestType(builder, requestType):
    ValidationRequestAddRequestType(builder, requestType)

def ValidationRequestAddRequest(builder, request):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)

def AddRequest(builder, request):
    ValidationRequestAddRequest(builder, request)

def ValidationRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ValidationRequestEnd(builder)
