// Copyright (c) 2025 The TensorCash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit/.

//! Cryptographic primitives: SPAKE2 PAKE and Noise protocol

pub mod test_mode;

use anyhow::{Context, Result};
use hkdf::Hkdf;
use sha2::{Digest, Sha256};
use snow::{Builder, HandshakeState, TransportState};
use spake2::{Ed25519Group, Identity, Password, Spake2};

// TODO: Integrate crypto primitives with transport layer
#[allow(dead_code)]
const NOISE_PATTERN: &str = "Noise_XX_25519_ChaChaPoly_BLAKE2b";

// EFF Short Wordlist (1296 words) - subset for SAS generation
// Full list: https://www.eff.org/files/2016/09/08/eff_short_wordlist_1.txt
// Using first 2048 words for better entropy (2048 = 2^11 = 11 bits per word)
const EFF_WORDLIST: &[&str] = &[
    "acid",
    "acorn",
    "acre",
    "acts",
    "afar",
    "affix",
    "aged",
    "agent",
    "agile",
    "aging",
    "agony",
    "agree",
    "ahead",
    "aide",
    "aids",
    "aim",
    "ajar",
    "alarm",
    "alias",
    "alibi",
    "alien",
    "alike",
    "alive",
    "aloe",
    "alone",
    "along",
    "aloof",
    "aloud",
    "alpha",
    "alps",
    "also",
    "altar",
    "alter",
    "alto",
    "amber",
    "amend",
    "ample",
    "amuse",
    "angel",
    "anger",
    "angle",
    "ankle",
    "apple",
    "april",
    "apron",
    "aqua",
    "area",
    "arena",
    "argue",
    "arise",
    "armed",
    "armor",
    "army",
    "aroma",
    "array",
    "arrow",
    "arson",
    "art",
    "ashen",
    "ashes",
    "atlas",
    "atom",
    "attic",
    "audio",
    "aunt",
    "avoid",
    "awake",
    "award",
    "aware",
    "awash",
    "awful",
    "awoke",
    "axes",
    "axis",
    "axle",
    "azure",
    "bacon",
    "badge",
    "badly",
    "baker",
    "balsa",
    "banal",
    "banjo",
    "barge",
    "barn",
    "baron",
    "basal",
    "base",
    "basil",
    "bask",
    "batch",
    "bath",
    "baton",
    "blade",
    "blank",
    "blast",
    "blaze",
    "bleak",
    "blend",
    "bless",
    "blimp",
    "blind",
    "blink",
    "bliss",
    "blitz",
    "bloat",
    "blob",
    "block",
    "bloke",
    "blond",
    "blood",
    "bloom",
    "blown",
    "blues",
    "bluff",
    "blunt",
    "blurt",
    "blush",
    "boast",
    "boats",
    "bobby",
    "bode",
    "bogus",
    "boil",
    "bold",
    "bolt",
    "bomb",
    "bond",
    "bonus",
    "book",
    "booth",
    "boots",
    "boss",
    "botch",
    "both",
    "boxer",
    "brand",
    "brass",
    "brave",
    "bravo",
    "brawl",
    "bread",
    "break",
    "breed",
    "briar",
    "brick",
    "bride",
    "brim",
    "bring",
    "brink",
    "brisk",
    "broad",
    "broil",
    "broke",
    "brook",
    "broom",
    "brush",
    "brute",
    "buck",
    "build",
    "bulge",
    "bulk",
    "bully",
    "bunch",
    "bunny",
    "burn",
    "burst",
    "bus",
    "bush",
    "bust",
    "busy",
    "buzz",
    "cable",
    "cache",
    "cadet",
    "cage",
    "cake",
    "calm",
    "cameo",
    "canal",
    "candy",
    "cane",
    "canon",
    "cape",
    "card",
    "cargo",
    "carol",
    "carry",
    "carve",
    "case",
    "cash",
    "cause",
    "cedar",
    "chain",
    "chair",
    "chant",
    "chaos",
    "charm",
    "chase",
    "cheek",
    "cheer",
    "chef",
    "chess",
    "chest",
    "chick",
    "chief",
    "child",
    "chili",
    "chill",
    "chime",
    "chin",
    "chip",
    "chive",
    "choke",
    "chord",
    "chose",
    "chunk",
    "churn",
    "chute",
    "cider",
    "cigar",
    "cinch",
    "city",
    "civic",
    "civil",
    "clad",
    "claim",
    "clamp",
    "clang",
    "clank",
    "clash",
    "clasp",
    "class",
    "claw",
    "clay",
    "clean",
    "clear",
    "cleat",
    "cleft",
    "clerk",
    "click",
    "cliff",
    "climb",
    "cling",
    "clink",
    "cloak",
    "clock",
    "clone",
    "cloth",
    "cloud",
    "clout",
    "clove",
    "clown",
    "club",
    "cluck",
    "clump",
    "clung",
    "coach",
    "coast",
    "coat",
    "coax",
    "cod",
    "code",
    "coil",
    "coke",
    "cola",
    "cold",
    "colt",
    "coma",
    "come",
    "comic",
    "comma",
    "cone",
    "cope",
    "copy",
    "coral",
    "cork",
    "cost",
    "cot",
    "couch",
    "cough",
    "cover",
    "cozy",
    "crack",
    "craft",
    "cramp",
    "crane",
    "crank",
    "crate",
    "crave",
    "crawl",
    "crazy",
    "craze",
    "cream",
    "creed",
    "creek",
    "creep",
    "creme",
    "crepe",
    "crept",
    "crest",
    "crib",
    "cried",
    "crisp",
    "crook",
    "crop",
    "cross",
    "crow",
    "crowd",
    "crown",
    "crude",
    "cruel",
    "cruise",
    "crumb",
    "crush",
    "crust",
    "cub",
    "curb",
    "cure",
    "curl",
    "curry",
    "curse",
    "curve",
    "curvy",
    "cushy",
    "cut",
    "cycle",
    "dad",
    "daily",
    "dairy",
    "daisy",
    "dance",
    "dandy",
    "darn",
    "dart",
    "dash",
    "data",
    "date",
    "dawn",
    "deaf",
    "deal",
    "dean",
    "debit",
    "debt",
    "debug",
    "decaf",
    "decal",
    "decay",
    "deck",
    "decor",
    "decoy",
    "deed",
    "delay",
    "denim",
    "dense",
    "dent",
    "depth",
    "derby",
    "desk",
    "dial",
    "diary",
    "dice",
    "dig",
    "dill",
    "dime",
    "dimly",
    "diner",
    "dingy",
    "disco",
    "dish",
    "disk",
    "ditch",
    "ditto",
    "ditty",
    "dive",
    "dizzy",
    "dock",
    "dodge",
    "doing",
    "doll",
    "donor",
    "donut",
    "dose",
    "dot",
    "doubt",
    "dove",
    "down",
    "dowry",
    "doze",
    "drab",
    "draft",
    "drag",
    "drain",
    "drank",
    "draw",
    "dream",
    "dress",
    "dried",
    "drift",
    "drill",
    "drink",
    "drive",
    "droit",
    "droll",
    "drone",
    "droop",
    "drove",
    "drown",
    "drum",
    "dry",
    "dual",
    "duck",
    "duct",
    "dude",
    "dug",
    "duke",
    "dull",
    "duly",
    "dumb",
    "dummy",
    "dump",
    "dune",
    "dunk",
    "dusk",
    "dust",
    "duty",
    "dwarf",
    "dwell",
    "e
ager",
    "eagle",
    "early",
    "earth",
    "easel",
    "east",
    "eaten",
    "eats",
    "ebony",
    "echo",
    "edge",
    "edgy",
    "elbow",
    "elder",
    "elect",
    "elk",
    "elm",
    "elope",
    "elude",
    "elves",
    "email",
    "emit",
    "empty",
    "emu",
    "enter",
    "entry",
    "equal",
    "erase",
    "error",
    "erupt",
    "essay",
    "ether",
    "ethic",
    "evade",
    "even",
    "evict",
    "evil",
    "evoke",
    "exact",
    "exam",
    "excel",
    "exert",
    "exile",
    "exist",
    "exit",
    "expel",
    "extol",
    "extra",
    "eyed",
    "fable",
    "faced",
    "fact",
    "fade",
    "fail",
    "faint",
    "fairy",
    "faith",
    "fake",
    "fall",
    "false",
    "fancy",
    "fang",
    "fax",
    "feast",
    "feed",
    "femur",
    "fence",
    "fend",
    "fetal",
    "fetch",
    "fever",
    "fiber",
    "fifth",
    "fifty",
    "fig",
    "fight",
    "film",
    "filth",
    "final",
    "finch",
    "fit",
    "five",
    "fix",
    "fizz",
    "fjord",
    "flack",
    "flag",
    "flail",
    "flair",
    "flak",
    "flake",
    "flame",
    "flank",
    "flap",
    "flash",
    "flask",
    "flat",
    "flaw",
    "flax",
    "flea",
    "fled",
    "fleet",
    "flesh",
    "flick",
    "fling",
    "flint",
    "flip",
    "flirt",
    "float",
    "flock",
    "flood",
    "floor",
    "flop",
    "floss",
    "flour",
    "flout",
    "flow",
    "flown",
    "flub",
    "flue",
    "fluff",
    "fluid",
    "fluke",
    "flung",
    "flunk",
    "flush",
    "flute",
    "flux",
    "fly",
    "foam",
    "foe",
    "fog",
    "foil",
    "foist",
    "fold",
    "folk",
    "fond",
    "font",
    "food",
    "fool",
    "foot",
    "ford",
    "fore",
    "fork",
    "form",
    "fort",
    "forum",
    "found",
    "fox",
    "foyer",
    "frail",
    "frame",
    "frank",
    "fraud",
    "freak",
    "free",
    "fresh",
    "friar",
    "fried",
    "frill",
    "frisk",
    "frog",
    "from",
    "front",
    "frost",
    "froth",
    "frown",
    "froze",
    "fruit",
    "fry",
    "fudge",
    "fuel",
    "fugue",
    "full",
    "fully",
    "fumes",
    "fun",
    "fund",
    "funk",
    "funny",
    "fur",
    "fury",
    "fuse",
    "fuss",
    "fuzz",
    "fuzzy",
    "gaffe",
    "gag",
    "gain",
    "gala",
    "game",
    "gamma",
    "gap",
    "gas",
    "gate",
    "gauge",
    "gave",
    "gavel",
    "gawk",
    "gaze",
    "gear",
    "gecko",
    "geek",
    "gem",
    "gene",
    "genie",
    "genre",
    "gift",
    "gig",
    "gills",
    "given",
    "giver",
    "glad",
    "gland",
    "glare",
    "glass",
    "glaze",
    "gleam",
    "glean",
    "glide",
    "glint",
    "gloat",
    "globe",
    "gloom",
    "glory",
    "gloss",
    "glove",
    "glow",
    "glue",
    "glum",
    "glut",
    "gnaw",
    "gnome",
    "goal",
    "goat",
    "going",
    "gold",
    "golf",
    "gone",
    "gong",
    "good",
    "goof",
    "gore",
    "gory",
    "gosh",
    "got",
    "gouge",
    "gown",
    "grab",
    "grace",
    "grad",
    "grain",
    "grand",
    "grant",
    "grape",
    "graph",
    "grasp",
    "grass",
    "grave",
    "gravy",
    "gray",
    "graze",
    "great",
    "greed",
    "green",
    "greet",
    "grew",
    "grid",
    "grief",
    "grill",
    "grime",
    "grin",
    "grip",
    "grist",
    "grit",
    "groan",
    "groom",
    "grope",
    "gross",
    "group",
    "grove",
    "grow",
    "grub",
    "grunt",
    "guard",
    "guess",
    "guest",
    "guide",
    "guild",
    "guilt",
    "guise",
    "gulf",
    "gulp",
    "gum",
    "guru",
    "gust",
    "gusto",
    "gusty",
    "guy",
    "habit",
    "hack",
    "hag",
    "hail",
    "hair",
    "half",
    "halt",
    "happy",
    "harm",
    "hash",
    "hasty",
    "hatch",
    "hate",
    "haven",
    "havoc",
    "hawk",
    "hazel",
    "hazy",
    "heap",
    "heat",
    "heave",
    "heavy",
    "hedge",
    "hefty",
    "heir",
    "helix",
    "hello",
    "helm",
    "help",
    "hemp",
    "hen",
    "heron",
    "hers",
    "hub",
    "hug",
    "hula",
    "hull",
    "human",
    "humid",
    "humor",
    "hump",
    "hung",
    "hunk",
    "hunt",
    "hurry",
    "hurt",
    "hush",
    "hut",
    "hydro",
    "hyena",
    "hymn",
    "icing",
    "icon",
    "icy",
    "ideal",
    "idiom",
    "idiot",
    "idle",
    "idly",
    "igloo",
    "image",
    "imam",
    "imp",
    "index",
    "ink",
    "input",
    "irate",
    "iris",
    "iron",
    "islam",
    "issue",
    "item",
    "ivory",
    "ivy",
    "jab",
    "jack",
    "jade",
    "jail",
    "jangle",
    "jar",
    "java",
    "jazz",
    "jeans",
    "jeep",
    "jeer",
    "jelly",
    "jerk",
    "jest",
    "jet",
    "jiffy",
    "job",
    "jog",
    "john",
    "join",
    "joint",
    "joke",
    "joker",
    "jolly",
    "jolt",
    "jostle",
    "joy",
    "judge",
    "judo",
    "juice",
    "juicy",
    "july",
    "jumbo",
    "jump",
    "jumpy",
    "june",
    "junk",
    "jury",
    "just",
    "kale",
    "karma",
    "kebab",
    "keep",
    "keg",
    "kept",
    "kick",
    "kilt",
    "kind",
    "king",
    "kink",
    "kiosk",
    "kiss",
    "kit",
    "kite",
    "kitty",
    "kiwi",
    "knee",
    "kneel",
    "knew",
    "knife",
    "knit",
    "knob",
    "knock",
    "knot",
    "known",
    "koala",
    "krill",
    "label",
    "lace",
    "lack",
    "lad",
    "laden",
    "ladle",
    "lady",
    "lair",
    "lake",
    "lam",
    "lama",
    "lamb",
    "lame",
    "lamp",
    "land",
    "lane",
    "lap",
    "lapse",
    "large",
    "lark",
    "lash",
    "lasso",
    "last",
    "latch",
    "late",
    "lather",
    "latte",
    "laugh",
    "lava",
    "law",
    "lawn",
    "lax",
    "layer",
    "lazy",
    "lead",
    "leaf",
    "leaky",
    "lean",
    "leap",
    "learn",
    "lease",
    "leash",
    "least",
    "leave",
    "left",
    "legal",
    "lemon",
    "lend",
    "lens",
    "lent",
    "leo",
    "less",
    "level",
    "lever",
    "liar",
    "libel",
    "lice",
    "lick",
    "lid",
    "life",
    "lift",
    "light",
    "like",
    "lil",
    "lilt",
    "lily",
    "limb",
    "limes",
    "limit",
    "limo",
    "limp",
    "line",
    "linen",
    "liner",
    "lingo",
    "link",
    "lint",
    "lion",
    "lip",
    "list",
    "lite",
    "liter",
    "lithe",
    "live",
    "liver",
    "livid",
    "llama",
    "load",
    "loaf",
    "loam",
    "loan",
    "lobby",
    "lobe",
    "local",
    "lock",
    "locus",
    "lodge",
    "loft",
    "lofty",
    "logic",
    "login",
    "logo",
    "loin",
    "long",
    "look",
    "loom",
    "loon",
    "loop",
    "loose",
    "loot",
    "lope",
    "lord",
    "lore",
    "lose",
    "loss",
    "lost",
    "lot",
    "lotto",
    "lotus",
    "loud",
    "lounge",
    "louse",
    "lousy",
    "lout",
    "love",
    "low",
    "loyal",
    "lucid",
    "luck",
    "lug",
    "lull",
    "lumbo",
    "lumen",
    "lumpy",
    "lunar",
    "lunch",
    "lung",
    "lunge",
    "lurch",
    "lure",
    "lurk",
    "lush",
    "lust",
    "lute",
    "lying",
    "lymph",
    "lynx",
    "lyre",
    "macro",
    "madam",
    "magic",
    "magma",
    "maid",
    "mail",
    "maim",
    "main",
    "make",
    "malar",
    "male",
    "mall",
    "malt",
    "mama",
    "mambo",
    "mamma",
    "man",
    "mango",
    "manor",
    "many",
    "map",
    "maple",
    "march",
    "mare",
    "mark",
    "mars",
    "mask",
    "mass",
    "mast",
    "match",
    "mate",
    "math",
    "maw",
    "maxim",
    "maybe",
    "mayor",
    "maze",
    "mead",
    "meal",
    "mean",
    "meat",
    "mecca",
    "medal",
    "media",
    "medic",
    "meek",
    "meet",
    "mega",
    "melee",
    "melon",
    "melt",
    "memo",
    "men",
    "mend",
    "menu",
    "meow",
    "mercy",
    "mere",
    "merge",
    "merit",
    "merry",
    "mesh",
    "mess",
    "metal",
    "metro",
    "micro",
    "midge",
    "midst",
    "might",
    "mild",
    "mile",
    "milk",
    "mill",
    "milt",
    "mime",
    "mimed",
    "mimic",
    "mince",
    "mind",
    "mine",
    "mini",
    "mink",
    "minor",
    "mint",
    "minus",
    "mire",
    "mirth",
    "miser",
    "miss",
    "mist",
    "mite",
    "mitt",
    "mix",
    "moan",
    "moat",
    "mob",
    "mocha",
    "mock",
    "mode",
    "model",
    "modem",
    "moist",
    "molar",
    "mold",
    "mole",
    "molt",
    "mom",
    "mona",
    "money",
    "monk",
    "month",
    "moody",
    "moon",
    "moor",
    "moose",
    "mop",
    "moral",
    "more",
    "morn",
    "morse",
    "most",
    "motel",
    "moth",
    "motor",
    "motto",
    "mound",
    "mount",
    "mourn",
    "mouse",
    "mousy",
    "mouth",
    "move",
    "mover",
    "movie",
    "mow",
    "mower",
    "much",
    "muck",
    "mud",
    "mug",
    "mule",
    "mull",
    "mum",
    "mummy",
    "munch",
    "mung",
    "mural",
    "murk",
    "murky",
    "muse",
    "mush",
    "music",
    "musk",
    "musky",
    "must",
    "mute",
    "mutt",
    "my",
    "myth",
    "nacho",
    "nag",
    "nail",
    "name",
    "nanny",
    "nape",
    "nappy",
    "narrow",
    "nasal",
    "nasty",
    "navy",
    "near",
    "neat",
    "neck",
    "need",
    "neon",
    "nephew",
    "nerd",
    "nerve",
    "nest",
    "net",
    "new",
    "newt",
    "next",
    "niece",
    "nifty",
    "nimble",
    "nine",
    "ninja",
    "nip",
    "noble",
    "nod",
    "node",
    "noise",
    "noisy",
    "nomad",
    "none",
    "nook",
    "noon",
    "noose",
    "norm",
    "north",
    "nose",
    "nosy",
    "notch",
    "note",
    "noun",
    "novel",
    "now",
    "nozzle",
    "null",
    "numb",
    "nurse",
    "nut",
    "nylon",
    "oaf",
    "oak",
    "oar",
    "oasis",
    "oath",
    "obese",
    "obey",
    "oboe",
    "occur",
    "ocean",
    "ocelot",
    "odd",
    "ode",
    "odor",
    "off",
    "offer",
    "often",
    "oil",
    "oink",
    "okay",
    "old",
    "olive",
    "omen",
    "omit",
    "once",
    "one",
    "onion",
    "only",
    "ooze",
    "opal",
    "open",
    "opera",
    "opt",
    "optic",
    "opus",
    "oral",
    "orange",
    "orbit",
    "orca",
    "orchid",
    "order",
    "ore",
    "organ",
    "origin",
    "orphan",
    "otter",
    "ouch",
    "ought",
    "ounce",
    "our",
    "out",
    "outdo",
    "outer",
    "output",
    "oval",
    "oven",
    "over",
    "overt",
    "owe",
    "owing",
    "owl",
    "own",
    "owner",
    "oxide",
    "ozone",
    "pace",
    "pack",
    "pact",
    "pad",
    "page",
    "pager",
    "pail",
    "pain",
    "paint",
    "pair",
    "pal",
    "palm",
    "pamper",
    "pan",
    "panda",
    "panel",
    "pang",
    "panic",
    "pansy",
    "pant",
    "panther",
    "papa",
    "papaya",
    "paper",
    "par",
    "parcel",
    "parch",
    "parent",
    "park",
    "parrot",
    "parse",
    "part",
    "party",
    "pass",
    "past",
    "pasta",
    "paste",
    "patch",
    "pate",
    "path",
    "patio",
    "patsy",
    "patty",
    "pause",
    "pave",
    "paw",
    "pawn",
    "pay",
    "payer",
    "payoff",
    "peace",
    "peach",
    "peak",
    "peanut",
    "pear",
    "pearl",
    "pecan",
    "peck",
    "pedal",
    "peek",
    "peel",
    "peep",
    "peer",
    "peg",
    "pelican",
    "pelt",
    "pen",
    "penal",
    "pence",
    "pencil",
    "penny",
    "pep",
    "pepper",
    "per",
    "perch",
    "period",
    "perk",
    "perky",
    "perm",
    "permit",
    "perp",
    "perry",
    "person",
    "pest",
    "pet",
    "petal",
    "petri",
    "petty",
    "pew",
    "phase",
    "phish",
    "phone",
    "photo",
    "phrase",
    "piano",
    "pick",
    "pickle",
    "picky",
    "picnic",
    "pie",
    "piece",
    "pier",
    "piety",
    "pig",
    "pigeon",
    "piggy",
    "pike",
    "pile",
    "pill",
    "pillow",
    "pilot",
    "pimp",
    "pin",
    "pinch",
    "pine",
    "ping",
    "pink",
    "pint",
    "pious",
    "pipe",
    "piper",
    "piracy",
    "pistol",
    "pit",
    "pitch",
    "pity",
    "pivot",
    "pixel",
    "pixie",
    "pizza",
    "place",
    "plaid",
    "plain",
    "plan",
    "plane",
    "plank",
    "plant",
    "plaza",
    "plate",
    "platter",
    "play",
    "plaza",
    "plea",
    "plead",
    "please",
    "pleat",
    "pledge",
    "plenty",
    "plight",
    "plod",
    "plop",
    "plot",
    "plow",
    "ploy",
    "pluck",
    "plug",
    "plum",
    "plumb",
    "plume",
    "plump",
    "plunge",
    "plunk",
    "plus",
    "plush",
    "poach",
    "pod",
    "poem",
    "poet",
    "point",
    "poise",
    "poison",
    "poke",
    "poker",
    "polar",
    "pole",
    "police",
    "policy",
    "polio",
    "polish",
    "polka",
    "poll",
    "polo",
    "polyp",
    "pond",
    "pony",
    "pooch",
    "poof",
    "pool",
    "poop",
    "poor",
    "pop",
    "pope",
    "poppy",
    "porch",
    "pore",
    "pork",
    "port",
    "pose",
    "posh",
    "post",
    "posy",
    "pot",
    "potato",
    "potion",
    "potter",
    "pouch",
    "pound",
    "pour",
    "pout",
    "powder",
    "power",
    "prank",
    "prawn",
    "pray",
    "prep",
    "press",
    "prey",
    "price",
    "pride",
    "pried",
    "prim",
    "prime",
    "print",
    "prior",
    "prism",
    "privy",
    "prize",
    "probe",
    "prof",
    "proof",
    "prop",
    "prose",
    "proud",
    "prove",
    "prowl",
    "proxy",
    "prude",
    "prune",
    "pry",
    "psalm",
    "pub",
    "puck",
    "puddle",
    "puff",
    "pug",
    "pull",
    "pulp",
    "pulse",
    "puma",
    "pump",
    "punch",
    "puny",
    "pup",
    "pupil",
    "puppy",
    "pure",
    "purge",
    "purple",
    "purr",
    "purse",
    "push",
    "put",
    "putt",
    "putz",
    "puzzle",
    "quack",
    "quad",
    "quail",
    "quake",
    "qualm",
    "quark",
    "quart",
    "quash",
    "quasi",
    "queen",
    "query",
    "quest",
    "queue",
    "quick",
    "quid",
    "quiet",
    "quill",
    "quilt",
    "quirk",
    "quit",
    "quiz",
    "quota",
    "quote",
    "rabbi",
    "rabbit",
    "rabid",
    "race",
    "rack",
    "racy",
    "radar",
    "radii",
    "radio",
    "radon",
    "raft",
    "rag",
    "rage",
    "raid",
    "rail",
    "rain",
    "raise",
    "rake",
    "rally",
    "ramp",
    "ranch",
    "range",
    "rank",
    "rant",
    "rap",
    "rapid",
    "rare",
    "rash",
    "rasp",
    "rat",
    "rate",
    "ratio",
    "rave",
    "raven",
    "raw",
    "ray",
    "raze",
    "razor",
    "reach",
    "react",
    "read",
    "ready",
    "real",
    "realm",
    "ream",
    "reap",
    "rear",
    "reason",
    "rebel",
    "reboot",
    "recall",
    "recap",
    "recede",
    "recipe",
    "recoil",
    "record",
    "recur",
    "red",
    "redo",
    "reduce",
    "reed",
    "reef",
    "reek",
    "reel",
    "refer",
    "refit",
    "reform",
    "refuge",
    "refund",
    "refuse",
    "regal",
    "regret",
    "rehab",
    "reign",
    "rein",
    "reject",
    "relax",
    "relay",
    "relic",
    "relief",
    "rely",
    "remain",
    "remark",
    "remedy",
    "remind",
    "remix",
    "remorse",
    "remote",
    "remove",
    "renal",
    "render",
    "renew",
    "rent",
    "rental",
    "reopen",
    "repair",
    "repay",
    "repeal",
    "repeat",
    "repel",
    "replay",
    "reply",
    "report",
    "repose",
    "rerun",
    "rescue",
    "resent",
    "reset",
    "reshoot",
    "reside",
    "residue",
    "resign",
    "resin",
    "resist",
    "resort",
    "rest",
    "result",
    "resume",
    "retail",
    "retain",
    "retina",
    "retire",
    "retro",
    "return",
    "reuse",
    "reveal",
    "revel",
    "review",
    "revise",
    "revive",
    "revoke",
    "revolt",
    "reward",
    "rewind",
    "rhino",
    "rhyme",
    "rib",
    "ribbon",
    "rice",
    "rich",
    "rid",
    "riddle",
    "ride",
    "rider",
    "ridge",
    "rifle",
    "rift",
    "rig",
    "right",
    "rigid",
    "rigor",
    "rim",
    "rind",
    "ring",
    "rink",
    "rinse",
    "riot",
    "rip",
    "ripe",
    "ripen",
    "rise",
    "risen",
    "riser",
    "risk",
    "risky",
    "rite",
    "ritual",
    "rival",
    "river",
    "roach",
    "road",
    "roam",
    "roar",
    "roast",
    "rob",
    "robe",
    "robin",
    "robot",
    "rock",
    "rocket",
    "rocky",
    "rod",
    "rode",
    "rodent",
    "rodeo",
    "rogue",
    "role",
    "roll",
    "roman",
    "romp",
    "roof",
    "rook",
    "rookie",
    "room",
    "roomy",
    "roost",
    "root",
    "rope",
    "rose",
    "rosy",
    "rot",
    "rotor",
    "rouge",
    "rough",
    "round",
    "rouse",
    "route",
    "rove",
    "rover",
    "row",
    "royal",
    "rub",
    "rubber",
    "rubble",
    "rubric",
    "ruby",
    "ruck",
    "rudder",
    "rude",
    "rue",
    "rug",
    "ruin",
    "rule",
    "ruler",
    "rum",
    "rumble",
    "rumen",
    "rumor",
    "rump",
    "run",
    "rung",
    "runner",
    "runny",
    "runt",
    "runway",
    "rural",
    "ruse",
    "rush",
    "rust",
    "rustic",
    "rusty",
    "rut",
    "sac",
    "sad",
    "saddle",
    "sadly",
    "safe",
    "saffron",
    "sag",
    "saga",
    "sage",
    "sago",
    "said",
    "sail",
    "saint",
    "sake",
    "salad",
    "salary",
    "sale",
    "salem",
    "saline",
    "salon",
    "saloon",
    "salsa",
    "salt",
    "salty",
    "salute",
    "salve",
    "samba",
    "same",
    "sample",
    "sand",
    "sandy",
    "sane",
    "sang",
    "sank",
    "santa",
    "sap",
    "sappy",
    "sash",
    "sass",
    "sassy",
    "sat",
    "satan",
    "satin",
    "satire",
    "sauce",
    "saucy",
    "sauna",
    "savage",
    "save",
    "saver",
    "savor",
    "savory",
    "savvy",
    "saw",
    "sax",
    "say",
    "scab",
    "scald",
    "scale",
    "scalf",
    "scam",
    "scan",
    "scar",
    "scare",
    "scarf",
    "scary",
    "scene",
    "scent",
    "scheme",
    "schism",
    "school",
    "scope",
    "scorch",
    "score",
    "scorn",
    "scout",
    "scowl",
    "scram",
    "scrap",
    "scrape",
    "scratch",
    "scrawl",
    "scream",
    "screen",
    "screw",
    "scribe",
    "scrimp",
    "scrip",
    "script",
    "scroll",
    "scrub",
    "scrum",
    "scuba",
    "scuff",
    "sculpt",
    "scurry",
    "scythe",
    "sea",
    "seal",
    "seam",
    "search",
    "season",
    "seat",
    "second",
    "secret",
    "sect",
    "sector",
    "secure",
    "sedan",
    "sedate",
    "seduce",
    "see",
    "seed",
    "seedy",
    "seek",
    "seem",
    "seen",
    "seep",
    "seer",
    "seesaw",
    "segment",
    "seize",
    "seldom",
    "select",
    "self",
    "sell",
    "seller",
    "semi",
    "senate",
    "send",
    "sender",
    "senior",
    "sense",
    "sent",
    "sentry",
    "sepia",
    "sequel",
    "sequin",
    "serene",
    "serial",
    "series",
    "serif",
    "sermon",
    "serum",
    "serve",
    "server",
    "sesame",
    "set",
    "setback",
    "setter",
    "settle",
    "setup",
    "seven",
    "sever",
    "severe",
    "sew",
    "sewage",
    "sewer",
    "shack",
    "shade",
    "shadow",
    "shady",
    "shaft",
    "shag",
    "shah",
    "shake",
    "shaken",
    "shaker",
    "shaky",
    "shale",
    "shall",
    "shallow",
    "sham",
    "shame",
    "shampoo",
    "shamrock",
    "shank",
    "shanty",
    "shape",
    "shard",
    "share",
    "shark",
    "sharp",
    "shave",
    "shaven",
    "shaver",
    "shawl",
    "she",
    "shear",
    "sheath",
    "shed",
    "sheen",
    "sheep",
    "sheer",
    "sheet",
    "sheik",
    "shelf",
    "shell",
    "shelter",
    "shelve",
    "sherbet",
    "sheriff",
    "sherry",
    "shield",
    "shift",
    "shifty",
    "shill",
    "shimmer",
    "shin",
    "shine",
    "shiny",
    "ship",
    "shire",
    "shirk",
    "shirt",
    "shiver",
    "shoal",
    "shock",
    "shoe",
    "shone",
    "shoo",
    "shook",
    "shoot",
    "shop",
    "shore",
    "shorn",
    "short",
    "shot",
    "should",
    "shout",
    "shove",
    "shovel",
    "show",
    "shown",
    "showy",
    "shrank",
    "shred",
    "shrew",
    "shrewd",
    "shriek",
    "shrift",
    "shrill",
    "shrimp",
    "shrine",
    "shrink",
    "shrivel",
    "shroud",
    "shrub",
    "shrug",
    "shrunk",
    "shuck",
    "shudder",
    "shuffle",
    "shun",
    "shunt",
    "shush",
    "shut",
    "shy",
    "sibling",
    "sibyl",
    "sick",
    "side",
    "sidle",
    "siege",
    "sieve",
    "sift",
    "sigh",
    "sight",
    "sigma",
    "sign",
    "signal",
    "signet",
    "silent",
    "silicon",
    "silk",
    "silky",
    "sill",
    "silly",
    "silo",
    "silt",
    "silver",
    "sim",
    "simile",
    "simmer",
    "simple",
    "simply",
    "sin",
    "since",
    "sinew",
    "sing",
    "singe",
    "singer",
    "single",
    "sink",
    "sinner",
    "sinus",
    "sip",
    "siphon",
    "sir",
    "sire",
    "siren",
    "sirloin",
    "sisal",
    "sissy",
    "sister",
    "sit",
    "sitar",
    "sitcom",
    "site",
    "sitter",
    "six",
    "sixth",
    "sixty",
    "size",
    "skate",
    "skater",
    "skew",
    "skewer",
    "ski",
    "skid",
    "skier",
    "skies",
    "skiff",
    "skill",
    "skim",
    "skimp",
    "skimpy",
    "skin",
    "skinny",
    "skip",
    "skirt",
    "skit",
    "skull",
    "skunk",
    "sky",
    "slab",
    "slack",
    "slacks",
    "slag",
    "slain",
    "slalom",
    "slam",
    "slander",
    "slang",
    "slant",
    "slap",
    "slash",
    "slat",
    "slate",
    "slaw",
    "slay",
    "sleazy",
    "sled",
    "sleek",
    "sleep",
    "sleet",
    "sleeve",
    "sleigh",
    "slender",
    "slept",
    "slew",
    "slice",
    "slick",
    "slid",
    "slide",
    "slier",
    "slight",
    "slim",
    "slime",
    "slimy",
    "sling",
    "slink",
    "slinky",
    "slip",
    "slipper",
    "slit",
    "sliver",
    "slob",
    "slogan",
    "sloop",
    "slop",
    "slope",
    "sloppy",
    "slosh",
    "slot",
    "sloth",
    "slouch",
    "slough",
    "slow",
    "sludge",
    "slug",
    "sluggish",
    "sluice",
    "slum",
    "slumber",
    "slump",
    "slung",
    "slunk",
    "slur",
    "slurp",
    "slush",
    "sly",
    "smack",
    "small",
    "smart",
    "smash",
    "smear",
    "smell",
    "smelt",
    "smile",
    "smirk",
    "smite",
    "smith",
    "smock",
    "smog",
    "smoke",
    "smoker",
    "smoky",
    "smolder",
    "smooth",
    "smother",
    "smudge",
    "smug",
    "smuggle",
    "snack",
    "snafu",
    "snag",
    "snail",
    "snake",
    "snap",
    "snare",
    "snarl",
    "snatch",
    "snazzy",
    "sneak",
    "sneer",
    "sneeze",
    "snide",
    "sniff",
    "sniffle",
    "snip",
    "snipe",
    "sniper",
    "snit",
    "snitch",
    "snob",
    "snoop",
    "snoopy",
    "snooze",
    "snore",
    "snort",
    "snout",
    "snow",
    "snowy",
    "snub",
    "snuck",
    "snuff",
    "snug",
    "snuggle",
    "soak",
    "soap",
    "soapy",
    "soar",
    "sob",
    "sober",
    "soccer",
    "social",
    "sock",
    "socket",
    "sod",
    "soda",
    "sodium",
    "sofa",
    "soft",
    "soggy",
    "soil",
    "solar",
    "sold",
    "solder",
    "soldier",
    "sole",
    "solemn",
    "solid",
    "solo",
    "solve",
    "somber",
    "some",
    "son",
    "sonar",
    "song",
    "sonic",
    "sonnet",
    "soon",
    "soot",
    "soothe",
    "soprano",
    "sorbet",
    "sorcery",
    "sordid",
    "sore",
    "sorrow",
    "sorry",
    "sort",
    "sought",
    "soul",
    "sound",
    "soup",
    "sour",
    "source",
    "south",
    "soy",
    "spa",
    "space",
    "spacey",
    "spade",
    "spam",
    "span",
    "spank",
    "spar",
    "spare",
    "spark",
    "sparse",
    "spasm",
    "spat",
    "spawn",
    "speak",
    "spear",
    "spec",
    "speck",
    "speech",
    "speed",
    "speedy",
    "spell",
    "spend",
    "spent",
    "spew",
    "sphere",
    "spice",
    "spicy",
    "spider",
    "spied",
    "spiel",
    "spike",
    "spiky",
    "spill",
    "spilt",
    "spin",
    "spine",
    "spiny",
    "spiral",
    "spire",
    "spirit",
    "spit",
    "spite",
    "splash",
    "splat",
    "splay",
    "spleen",
    "splice",
    "splint",
    "split",
    "splotch",
    "splurge",
    "spoil",
    "spoke",
    "sponge",
    "spoof",
    "spook",
    "spooky",
    "spool",
    "spoon",
    "spore",
    "sport",
    "spot",
    "spouse",
    "spout",
    "sprain",
    "sprang",
    "sprawl",
    "spray",
    "spread",
    "spree",
    "sprig",
    "spring",
    "sprint",
    "sprite",
    "sprout",
    "spruce",
    "sprung",
    "spry",
    "spud",
    "spun",
    "spunk",
    "spur",
    "spurn",
    "spurt",
    "spy",
    "squad",
    "squash",
    "squat",
    "squaw",
    "squawk",
    "squeak",
    "squeal",
    "squeeze",
    "squid",
    "squint",
    "squire",
    "squirm",
    "squirt",
    "squish",
    "stab",
    "stable",
    "stack",
    "staff",
    "stag",
    "stage",
    "staid",
    "stain",
    "stair",
    "stake",
    "stale",
    "stalk",
    "stall",
    "stamp",
    "stance",
    "stand",
    "stank",
    "staple",
    "star",
    "starch",
    "stare",
    "stark",
    "start",
    "starve",
    "stash",
    "state",
    "static",
    "statue",
    "status",
    "staunch",
    "stave",
    "stay",
    "stead",
    "steady",
    "steak",
    "steal",
    "steam",
    "steed",
    "steel",
    "steep",
    "steer",
    "stein",
    "stem",
    "stench",
    "step",
    "stereo",
    "stern",
    "stew",
    "stick",
    "sticky",
    "stiff",
    "stifle",
    "still",
    "stilt",
    "sting",
    "stink",
    "stinky",
    "stint",
    "stir",
    "stitch",
    "stoat",
    "stock",
    "stoic",
    "stoke",
    "stole",
    "stomp",
    "stone",
    "stony",
    "stood",
    "stool",
    "stoop",
    "stop",
    "store",
    "stork",
    "storm",
    "stormy",
    "story",
    "stout",
    "stove",
    "stow",
    "straddle",
    "strafe",
    "straight",
    "strain",
    "strait",
    "strand",
    "strange",
    "strap",
    "strata",
    "straw",
    "stray",
    "streak",
    "stream",
    "street",
    "stress",
    "stretch",
    "strew",
    "strict",
    "stride",
    "strife",
    "strike",
    "string",
    "strip",
    "stripe",
    "strive",
    "strobe",
    "strode",
    "stroke",
    "stroll",
    "strong",
    "strove",
    "struck",
    "strung",
    "strut",
    "stub",
    "stuck",
    "stud",
    "studio",
    "study",
    "stuff",
    "stuffy",
    "stumble",
    "stump",
    "stun",
    "stung",
    "stunk",
    "stunt",
    "stupid",
    "sturdy",
    "stutter",
    "sty",
    "style",
    "stylus",
    "suave",
    "sub",
    "subdue",
    "subject",
    "sublime",
    "submit",
    "subnet",
    "subset",
    "subtle",
    "suburb",
    "subway",
    "succeed",
    "success",
    "succor",
    "such",
    "suck",
    "sucker",
    "sudden",
    "suds",
    "sue",
    "suede",
    "suffer",
    "suffix",
    "sugar",
    "suggest",
    "suit",
    "suite",
    "suitor",
    "sulfur",
    "sulk",
    "sulky",
    "sullen",
    "sultan",
    "sum",
    "sumac",
    "summit",
    "summon",
    "sumo",
    "sump",
    "sun",
    "sundae",
    "sunday",
    "sundry",
    "sung",
    "sunk",
    "sunken",
    "sunny",
    "sunrise",
    "sunset",
    "super",
    "superb",
    "supper",
    "supple",
    "supply",
    "support",
    "suppose",
    "supreme",
    "sure",
    "surf",
    "surface",
    "surge",
    "surgeon",
    "surgery",
    "surly",
    "surname",
    "surplus",
    "surreal",
    "survey",
    "survive",
    "sushi",
    "suspect",
    "suspend",
    "suspense",
    "sustain",
    "suture",
    "svelte",
    "swab",
    "swagger",
    "swallow",
    "swam",
    "swami",
    "swamp",
    "swampy",
    "swan",
    "swap",
    "swarm",
    "swarthy",
    "swat",
    "swatch",
    "swath",
    "sway",
    "swear",
    "sweat",
    "sweater",
    "sweaty",
    "sweep",
    "sweet",
    "swell",
    "swept",
    "swerve",
    "swift",
    "swig",
    "swill",
    "swim",
    "swimmer",
    "swindle",
    "swine",
    "swing",
    "swipe",
    "swirl",
    "swish",
    "swiss",
    "switch",
    "swivel",
    "swollen",
    "swoon",
    "swoop",
    "sword",
    "swore",
    "sworn",
    "swum",
    "swung",
    "sycamore",
    "syllable",
    "sylph",
    "symbol",
    "sync",
    "synod",
    "syntax",
    "syrup",
    "system",
    "tab",
    "table",
    "tablet",
    "taboo",
    "tabular",
    "tacit",
    "tack",
    "tackle",
    "tacky",
    "taco",
    "tact",
    "tactful",
    "tactic",
    "tactile",
    "tad",
    "tadpole",
    "taffy",
    "tag",
    "tail",
    "tailor",
    "taint",
    "take",
    "taken",
    "taker",
    "talc",
    "tale",
    "talent",
    "talk",
    "talker",
    "tall",
    "taller",
    "tallow",
    "tally",
    "talon",
    "tamale",
    "tambourine",
    "tame",
    "tamer",
    "tamp",
    "tamper",
    "tan",
    "tandem",
    "tang",
    "tangent",
    "tangle",
    "tango",
    "tangy",
    "tank",
    "tanker",
    "tanner",
    "tantrum",
    "tap",
    "tape",
    "taper",
    "tapestry",
    "tar",
    "tardy",
    "target",
    "tariff",
    "tarmac",
    "tarnish",
    "tarot",
    "tarp",
    "tarpon",
    "tarragon",
    "tart",
    "tartar",
    "task",
    "tassel",
    "taste",
    "tasty",
    "tat",
    "tatter",
    "tattle",
    "tattoo",
    "taunt",
    "taut",
    "tavern",
    "tawny",
    "tax",
    "taxi",
    "taxing",
    "tea",
    "teach",
    "teacher",
    "teak",
    "teal",
    "team",
    "tear",
    "tease",
    "teaspoon",
    "teat",
    "tech",
    "tee",
    "teem",
    "teen",
    "teeth",
    "teethe",
    "teller",
    "temp",
    "temper",
    "temple",
    "tempo",
    "tempt",
    "ten",
    "tenant",
    "tend",
    "tender",
    "tendon",
    "tendril",
    "tenet",
    "tenon",
    "tenor",
    "tense",
    "tension",
    "tent",
    "tenth",
    "tenure",
    "tepee",
    "tepid",
    "term",
    "terminal",
    "terrace",
    "terrain",
    "terrible",
    "terrier",
    "terrify",
    "terror",
    "terry",
    "terse",
    "test",
    "tester",
    "testy",
    "text",
    "texture",
    "than",
    "thank",
    "thanks",
    "that",
    "thaw",
    "the",
    "theater",
    "thee",
    "theft",
    "their",
    "them",
    "theme",
    "then",
    "thence",
    "theory",
    "therapy",
    "there",
    "thermal",
    "these",
    "thesis",
    "they",
    "thick",
    "thicken",
    "thief",
    "thigh",
    "thimble",
    "thin",
    "thing",
    "think",
    "thinker",
    "third",
    "thirst",
    "thirsty",
    "this",
    "thistle",
    "thong",
    "thorn",
    "thorny",
    "those",
    "though",
    "thought",
    "thrash",
    "thread",
    "threat",
    "three",
    "thresh",
    "threw",
    "thrift",
    "thrifty",
    "thrill",
    "thrive",
    "throat",
    "throaty",
    "throb",
    "throne",
    "throng",
    "through",
    "throw",
    "thrown",
    "thrust",
    "thud",
    "thug",
    "thumb",
    "thump",
    "thunder",
    "thus",
    "thwart",
    "thyself",
    "tiara",
    "tibia",
    "tic",
    "tick",
    "ticket",
    "tickle",
    "tidal",
    "tide",
    "tidy",
    "tie",
    "tier",
    "tiff",
    "tiger",
    "tight",
    "tighten",
    "tights",
    "tile",
    "till",
    "tiller",
    "tilt",
    "timber",
    "time",
    "timer",
    "timid",
    "timing",
    "tin",
    "tinder",
    "tine",
    "tinge",
    "tingle",
    "tinker",
    "tinkle",
    "tinsel",
    "tint",
    "tiny",
    "tip",
    "tipper",
    "tipsy",
    "tiptoe",
    "tirade",
    "tire",
    "tired",
    "tissue",
    "titan",
    "tithe",
    "title",
    "toad",
    "toast",
    "toaster",
    "toasty",
    "today",
    "toddle",
    "toddler",
    "toe",
    "toffee",
    "tofu",
    "toga",
    "together",
    "toggle",
    "toil",
    "toilet",
    "token",
    "told",
    "toll",
    "tom",
    "tomato",
    "tomb",
    "tomboy",
    "tome",
    "ton",
    "tonal",
    "tone",
    "tong",
    "tongue",
    "tonic",
    "tonight",
    "tonsil",
    "too",
    "took",
    "tool",
    "toot",
    "tooth",
    "toothy",
    "top",
    "topaz",
    "topic",
    "topical",
    "topple",
    "torch",
    "tore",
    "torn",
    "tornado",
    "torpedo",
    "torque",
    "torrent",
    "torrid",
    "torso",
    "tort",
    "tortoise",
    "torture",
    "torus",
    "toss",
    "total",
    "totem",
    "totter",
    "toucan",
    "touch",
    "touchy",
    "tough",
    "toughen",
    "tour",
    "tourist",
    "tousle",
    "tout",
    "tow",
    "toward",
    "towel",
    "tower",
    "town",
    "toxic",
    "toxin",
    "toy",
    "trace",
    "track",
    "tract",
    "tractor",
    "trade",
    "trader",
    "traffic",
    "tragedy",
    "tragic",
    "trail",
    "trailer",
    "train",
    "trainer",
    "trait",
    "traitor",
    "tram",
    "tramp",
    "trance",
    "tranquil",
    "transit",
    "translate",
    "transmit",
    "trap",
    "trash",
    "trashy",
    "trauma",
    "travel",
    "traverse",
    "travesty",
    "trawl",
    "tray",
    "tread",
    "treason",
    "treat",
    "treaty",
    "treble",
    "tree",
    "trek",
    "trellis",
    "tremble",
    "tremendous",
    "tremor",
    "trench",
    "trend",
    "trendy",
    "trespass",
    "tress",
    "trestle",
    "triad",
    "trial",
    "triangle",
    "tribal",
    "tribe",
    "tribune",
    "tribute",
    "trice",
    "trick",
    "trickle",
    "tricky",
    "tried",
    "trifle",
    "trigger",
    "trill",
    "trillion",
    "trim",
    "trimmer",
    "trinity",
    "trinket",
    "trio",
    "trip",
    "tripe",
    "triple",
    "triplet",
    "tripod",
    "trite",
    "triumph",
    "trivia",
    "trivial",
    "trod",
    "troll",
    "trolley",
    "trombone",
    "troop",
    "trooper",
    "trophy",
    "tropic",
    "tropical",
    "trot",
    "trouble",
    "trough",
    "trounce",
    "troupe",
    "trousers",
    "trout",
    "trove",
    "trowel",
    "truce",
    "truck",
    "trudge",
    "true",
    "truffle",
    "truly",
    "trump",
    "trumpet",
    "trunk",
    "trust",
    "trustee",
    "trusty",
    "truth",
    "try",
    "tsar",
    "tsunami",
    "tub",
    "tuba",
    "tubby",
    "tube",
    "tubular",
    "tuck",
    "tuesday",
    "tuft",
    "tug",
    "tuition",
    "tulip",
    "tulle",
    "tumble",
    "tumor",
    "tumult",
    "tuna",
    "tundra",
    "tune",
    "tuner",
    "tunic",
    "tunnel",
    "turban",
    "turbine",
    "turbo",
    "turf",
    "turkey",
    "turmeric",
    "turmoil",
    "turn",
    "turner",
    "turnip",
    "turnout",
    "turtle",
    "tusk",
    "tussle",
    "tutor",
    "tutu",
    "tux",
    "tuxedo",
    "twang",
    "tweak",
    "tweed",
    "tweet",
    "tweezers",
    "twelve",
    "twenty",
    "twice",
    "twig",
    "twilight",
    "twin",
    "twine",
    "twinge",
    "twinkle",
    "twirl",
    "twist",
    "twister",
    "twisty",
    "twit",
    "twitch",
    "twitter",
    "two",
    "tycoon",
    "type",
    "typhoid",
    "typhoon",
    "typical",
    "typify",
    "typo",
    "tyrant",
    "udder",
    "ugly",
    "ukulele",
    "ulcer",
    "ulterior",
    "ultimate",
    "ultra",
    "umber",
    "umbrage",
    "umpire",
    "unable",
    "unaware",
    "unbeaten",
    "uncle",
    "uncover",
    "under",
    "undo",
    "undone",
    "unearth",
    "uneasy",
    "uneven",
    "unfair",
    "unfold",
    "ungainly",
    "unhappy",
    "unholy",
    "unicorn",
    "unified",
    "uniform",
    "unify",
    "union",
    "unique",
    "unison",
    "unit",
    "unite",
    "unity",
    "universe",
    "unjust",
    "unkempt",
    "unkind",
    "unknown",
    "unlace",
    "unlawful",
    "unleash",
    "unless",
    "unlike",
    "unload",
    "unlock",
    "unlucky",
    "unmask",
    "unmoved",
    "unnamed",
    "unpack",
    "unpaid",
    "unplug",
    "unquote",
    "unravel",
    "unrest",
    "unripe",
    "unruly",
    "unsafe",
    "unsaid",
    "unseat",
    "unseen",
    "unsold",
    "unsound",
    "unsung",
    "unsure",
    "untidy",
    "untie",
    "until",
    "unto",
    "untold",
    "untrue",
    "unused",
    "unusual",
    "unveil",
    "unwed",
    "unwell",
    "unwind",
    "unwise",
    "unwrap",
    "unyielding",
    "up",
    "upbeat",
    "upbraid",
    "upcoming",
    "update",
    "upgrade",
    "upheaval",
    "uphill",
    "uphold",
    "upkeep",
    "upland",
    "uplift",
    "upon",
    "upper",
    "upright",
    "uprising",
    "uproar",
    "uproot",
    "upset",
    "upshot",
    "upside",
    "upstage",
    "upstairs",
    "upstart",
    "upstream",
    "upsurge",
    "upswing",
    "uptake",
    "uptight",
    "uptown",
    "upturn",
    "upward",
    "uranium",
    "urban",
    "urbane",
    "urchin",
    "urge",
    "urgent",
    "urinal",
    "urine",
    "urn",
    "usage",
    "usable",
    "use",
    "used",
    "useful",
    "useless",
    "user",
    "usher",
    "usual",
    "usurp",
    "utensil",
    "uterus",
    "utility",
    "utilize",
    "utmost",
    "utopia",
    "utter",
    "vacancy",
    "vacant",
    "vacate",
    "vaccine",
    "vacuum",
    "vagabond",
    "vagrant",
    "vague",
    "vain",
    "vale",
    "valet",
    "valiant",
    "valid",
    "valley",
    "valor",
    "valuable",
    "value",
    "valve",
    "vampire",
    "van",
    "vandal",
    "vane",
    "vanguard",
    "vanilla",
    "vanish",
    "vanity",
    "vanquish",
    "vantage",
    "vapid",
    "vapor",
    "variable",
    "variant",
    "vary",
    "vase",
    "vast",
    "vat",
    "vault",
    "vaunt",
    "veal",
    "veer",
    "vegan",
    "vegetable",
    "vehicle",
    "veil",
    "vein",
    "velcro",
    "velocity",
    "velour",
    "velvet",
    "velvety",
    "vendor",
    "veneer",
    "venerate",
    "vengeance",
    "venison",
    "venom",
    "vent",
    "venture",
    "venue",
    "venus",
    "verb",
    "verbal",
    "verdict",
    "verge",
    "verify",
    "vermin",
    "verse",
    "version",
    "versus",
    "vertex",
    "vertical",
    "vertigo",
    "verve",
    "very",
    "vessel",
    "vest",
    "vestige",
    "vet",
    "veteran",
    "veto",
    "vex",
    "via",
    "viable",
    "viaduct",
    "vial",
    "vibrant",
    "vibrate",
    "vicar",
    "vice",
    "viceroy",
    "vicinity",
    "vicious",
    "victim",
    "victor",
    "victory",
    "video",
    "vie",
    "view",
    "vigil",
    "vigilant",
    "vigor",
    "vile",
    "villa",
    "village",
    "villain",
    "vim",
    "vindicate",
    "vine",
    "vinegar",
    "vineyard",
    "vintage",
    "vinyl",
    "viola",
    "violate",
    "violence",
    "violent",
    "violet",
    "violin",
    "viper",
    "viral",
    "virgin",
    "virgo",
    "virile",
    "virtual",
    "virtue",
    "virus",
    "visa",
    "visceral",
    "vise",
    "visible",
    "vision",
    "visit",
    "visitor",
    "visor",
    "vista",
    "visual",
    "vital",
    "vitamin",
    "vivid",
    "vixen",
    "vocal",
    "vocation",
    "vodka",
    "vogue",
    "voice",
    "void",
    "volatile",
    "volcanic",
    "volcano",
    "volt",
    "voltage",
    "volume",
    "voluntary",
    "volunteer",
    "vomit",
    "voodoo",
    "vortex",
    "vote",
    "voter",
    "vouch",
    "voucher",
    "vow",
    "vowel",
    "voyage",
    "vulgar",
    "vulnerable",
    "vulture",
    "wad",
    "waddle",
    "wade",
    "wafer",
    "waffle",
    "waft",
    "wag",
    "wage",
    "wager",
    "wagon",
    "waif",
    "wail",
    "waist",
    "wait",
    "waiter",
    "waive",
    "waiver",
    "wake",
    "waken",
    "walk",
    "walker",
    "wall",
    "wallet",
    "wallop",
    "wallow",
    "walnut",
    "walrus",
    "waltz",
    "wan",
    "wand",
    "wander",
    "wane",
    "want",
    "war",
    "warble",
    "ward",
    "warden",
    "wardrobe",
    "ware",
    "warehouse",
    "warfare",
    "warlike",
    "warm",
    "warmer",
    "warmth",
    "warn",
    "warp",
    "warrant",
    "warranty",
    "warren",
    "warrior",
    "wart",
    "wary",
    "was",
    "wash",
    "washer",
    "wasp",
    "waste",
    "wasteful",
    "watch",
    "watchdog",
    "water",
    "watery",
    "watt",
    "wattage",
    "wave",
    "waver",
    "wavy",
    "wax",
    "waxy",
    "way",
    "wayward",
    "we",
    "weak",
    "weaken",
    "wealth",
    "wealthy",
    "wean",
    "weapon",
    "wear",
    "weary",
    "weasel",
    "weather",
    "weave",
    "weaver",
    "web",
    "wed",
    "wedding",
    "wedge",
    "wednesday",
    "wee",
    "weed",
    "weedy",
    "week",
    "weekday",
    "weekend",
    "weekly",
    "weep",
    "weevil",
    "weigh",
    "weight",
    "weighty",
    "weir",
    "weird",
    "welcome",
    "weld",
    "welfare",
    "well",
    "welsh",
    "welt",
    "wench",
    "went",
    "wept",
    "were",
    "west",
    "western",
    "wet",
    "wetland",
    "whack",
    "whale",
    "whaler",
    "wharf",
    "what",
    "wheat",
    "wheel",
    "wheeze",
    "when",
    "whence",
    "where",
    "whet",
    "whether",
    "which",
    "whiff",
    "while",
    "whim",
    "whimper",
    "whimsy",
    "whine",
    "whinny",
    "whip",
    "whir",
    "whirl",
    "whisk",
    "whisker",
    "whiskey",
    "whisper",
    "whistle",
    "white",
    "whiten",
    "whittle",
    "whiz",
    "who",
    "whoa",
    "whoever",
    "whole",
    "whom",
    "whoop",
    "whoosh",
    "whopper",
    "whose",
    "why",
    "wick",
    "wicked",
    "wicker",
    "wide",
    "widen",
    "widespread",
    "widget",
    "widow",
    "widower",
    "width",
    "wield",
    "wife",
    "wig",
    "wiggle",
    "wild",
    "wildlife",
    "wile",
    "will",
    "willful",
    "willing",
    "willow",
    "willowy",
    "wilt",
    "wily",
    "wimp",
    "win",
    "wince",
    "winch",
    "wind",
    "window",
    "windpipe",
    "windy",
    "wine",
    "winery",
    "wing",
    "wink",
    "winner",
    "winning",
    "winnow",
    "winter",
    "wintry",
    "wipe",
    "wiper",
    "wire",
    "wiry",
    "wisdom",
    "wise",
    "wisely",
    "wish",
    "wispy",
    "wistful",
    "wit",
    "witch",
    "with",
    "withdraw",
    "wither",
    "withhold",
    "within",
    "without",
    "withstand",
    "witness",
    "witty",
    "wizard",
    "wobble",
    "wobbly",
    "woe",
    "wok",
    "woke",
    "wolf",
    "woman",
    "womb",
    "women",
    "won",
    "wonder",
    "wondrous",
    "wont",
    "woo",
    "wood",
    "wooden",
    "woodland",
    "woodpecker",
    "woodwind",
    "woody",
    "woof",
    "wool",
    "woolen",
    "woozy",
    "word",
    "wordy",
    "wore",
    "work",
    "worker",
    "workout",
    "workshop",
    "world",
    "worldly",
    "worm",
    "wormy",
    "worn",
    "worried",
    "worry",
    "worse",
    "worsen",
    "worship",
    "worst",
    "worth",
    "worthy",
    "would",
    "wound",
    "wove",
    "woven",
    "wow",
    "wrangle",
    "wrap",
    "wrapper",
    "wrath",
    "wreak",
    "wreath",
    "wreck",
    "wreckage",
    "wren",
    "wrench",
    "wrest",
    "wrestle",
    "wretch",
    "wretched",
    "wriggle",
    "wring",
    "wrinkle",
    "wrist",
    "writ",
    "write",
    "writer",
    "writhe",
    "writing",
    "written",
    "wrong",
    "wrote",
    "wrought",
    "wrung",
    "wry",
    "xerox",
    "yacht",
    "yak",
    "yam",
    "yang",
    "yank",
    "yap",
    "yard",
    "yarn",
    "yawn",
    "yeah",
    "year",
    "yearly",
    "yearn",
    "yeast",
    "yell",
    "yellow",
    "yelp",
    "yen",
    "yes",
    "yesterday",
    "yet",
    "yew",
    "yield",
    "yin",
    "yodel",
    "yoga",
    "yogurt",
    "yoke",
    "yokel",
    "yolk",
    "yonder",
    "yore",
    "you",
    "young",
    "younger",
    "your",
    "yourself",
    "youth",
    "youthful",
    "yowl",
    "yoyo",
    "yucca",
    "yuck",
    "yummy",
    "yuppie",
    "zap",
    "zeal",
    "zealot",
    "zealous",
    "zebra",
    "zen",
    "zenith",
    "zephyr",
    "zero",
    "zest",
    "zesty",
    "zigzag",
    "zilch",
    "zinc",
    "zing",
    "zip",
    "zipper",
    "zippy",
    "zit",
    "zodiac",
    "zombie",
    "zone",
    "zonked",
    "zoo",
    "zoom",
    "zucchini",
    "zulu",
];

/// Derive Noise PSK from SPAKE2 shared secret using HKDF-SHA256
/// This provides proper key hygiene by domain-separating the derived key
fn derive_noise_psk(shared_secret: &[u8]) -> Result<Vec<u8>> {
    let hkdf = Hkdf::<Sha256>::new(None, shared_secret);
    let mut psk = vec![0u8; 32]; // 32 bytes for Noise PSK
    hkdf.expand(b"cosign-noise-psk-v1", &mut psk)
        .map_err(|_| anyhow::anyhow!("HKDF expansion failed"))?;
    Ok(psk)
}

/// Derive SAS from Noise handshake hash
/// Returns 5 words from EFF wordlist (55 bits of entropy)
fn derive_sas_from_transcript(handshake_hash: &[u8]) -> String {
    // Hash the handshake_hash with SHA256 for additional mixing
    let mut hasher = Sha256::new();
    hasher.update(handshake_hash);
    let hash = hasher.finalize();

    // Extract 5 word indices (11 bits each = 2048 words per index)
    // Total entropy: 55 bits
    // We use a simpler approach: take consecutive bytes and map to word indices
    let mut words = Vec::with_capacity(5);

    for i in 0..5 {
        // Each word needs 11 bits for 2048 word space
        // Use 2 bytes (16 bits) per word for simplicity
        let byte_idx = i * 2;

        if byte_idx + 1 < hash.len() {
            // Read 2 bytes as u16
            let two_bytes = u16::from_be_bytes([hash[byte_idx], hash[byte_idx + 1]]);
            // Take lower 11 bits (0x7FF = 0b11111111111)
            let word_idx = (two_bytes & 0x7FF) as usize;
            // Map to wordlist with modulo for safety
            let final_idx = word_idx % EFF_WORDLIST.len().min(2048);
            words.push(EFF_WORDLIST[final_idx]);
        } else {
            // Fallback: use single byte with modulo
            let word_idx = (hash[byte_idx % hash.len()] as usize) % EFF_WORDLIST.len();
            words.push(EFF_WORDLIST[word_idx]);
        }
    }

    words.join("-")
}

// Wrapper to store SPAKE2 state with proper lifetimes
enum Spake2StateWrapper {
    Initiator(spake2::Spake2<Ed25519Group>),
    Responder(spake2::Spake2<Ed25519Group>),
}

pub struct CryptoSession {
    invite_code: String,
    #[allow(dead_code)]
    shared_secret: Option<Vec<u8>>,
    #[allow(dead_code)]
    noise_state: Option<NoiseState>,
    // Store SPAKE2 state for two-phase exchange
    spake2_state: Option<Spake2StateWrapper>,
    /// Handshake hash from Noise protocol (for SAS derivation)
    handshake_hash: Option<Vec<u8>>,
}

#[allow(dead_code)]
enum NoiseState {
    Handshake(Box<HandshakeState>),
    Transport(Box<TransportState>),
}

impl CryptoSession {
    /// Create a new crypto session with the given invite code (PAKE password)
    pub fn new(invite_code: &str) -> Result<Self> {
        Ok(Self {
            invite_code: invite_code.to_string(),
            shared_secret: None,
            noise_state: None,
            spake2_state: None,
            handshake_hash: None,
        })
    }

    /// Start SPAKE2 exchange and return outbound message
    /// Call this once to get the message to send to peer
    #[allow(dead_code)]
    pub fn spake2_start(&mut self, is_initiator: bool) -> Result<Vec<u8>> {
        log::debug!("Starting SPAKE2 exchange (initiator: {})", is_initiator);

        // Use the invite code as the PAKE password
        let password = Password::new(self.invite_code.as_bytes());

        // Create SPAKE2 instance and get outbound message
        // Both sides must use the same idA and idB in the same order
        let (state, outbound_msg) = if is_initiator {
            Spake2::<Ed25519Group>::start_a(
                &password,
                &Identity::new(b"initiator"),
                &Identity::new(b"responder"),
            )
        } else {
            Spake2::<Ed25519Group>::start_b(
                &password,
                &Identity::new(b"initiator"), // idA - same as start_a
                &Identity::new(b"responder"), // idB - same as start_a
            )
        };

        let outbound_vec = outbound_msg.to_vec();

        // Store the SPAKE2 state for finish() call
        self.spake2_state = Some(if is_initiator {
            Spake2StateWrapper::Initiator(state)
        } else {
            Spake2StateWrapper::Responder(state)
        });

        Ok(outbound_vec)
    }

    /// Complete SPAKE2 exchange with peer's message
    /// Call this after receiving peer's message to derive shared secret
    #[allow(dead_code)]
    pub fn spake2_finish(&mut self, _is_initiator: bool, peer_msg: &[u8]) -> Result<Vec<u8>> {
        log::debug!(
            "Completing SPAKE2 exchange, peer_msg len: {}",
            peer_msg.len()
        );

        // Take the stored SPAKE2 state
        let state = self
            .spake2_state
            .take()
            .ok_or_else(|| anyhow::anyhow!("Must call spake2_start() first"))?;

        // Complete the exchange with peer's message using the stored state
        let shared_secret = match state {
            Spake2StateWrapper::Initiator(s) => s.finish(peer_msg),
            Spake2StateWrapper::Responder(s) => s.finish(peer_msg),
        }
        .map_err(|e| anyhow::anyhow!("SPAKE2 key exchange failed: {:?}", e))?;

        self.shared_secret = Some(shared_secret.clone());
        log::debug!(
            "SPAKE2 exchange complete, derived {} byte secret",
            shared_secret.len()
        );

        Ok(shared_secret)
    }

    /// Initialize Noise protocol handshake using SPAKE2 shared secret
    /// Uses HKDF to derive the Noise PSK for proper key hygiene
    #[allow(dead_code)]
    pub fn init_noise(&mut self, is_initiator: bool) -> Result<()> {
        log::debug!("Initializing Noise protocol (initiator: {})", is_initiator);

        // Ensure we have a shared secret from SPAKE2
        let shared_secret = self
            .shared_secret
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("Must complete SPAKE2 exchange first"))?;

        // Derive PSK using HKDF for proper key hygiene
        let psk = derive_noise_psk(shared_secret)?;
        log::debug!("Derived Noise PSK using HKDF-SHA256");

        // Use Noise_NNpsk0 pattern which doesn't require static keys
        // NN = no static keys, psk0 = PSK at beginning
        let params = "Noise_NNpsk0_25519_ChaChaPoly_BLAKE2b"
            .parse()
            .map_err(|e| anyhow::anyhow!("Invalid Noise pattern: {:?}", e))?;

        let builder = Builder::new(params);
        let builder = builder.psk(0, &psk); // Use derived PSK

        let noise_state = if is_initiator {
            builder
                .build_initiator()
                .map_err(|e| anyhow::anyhow!("Failed to build Noise initiator: {:?}", e))?
        } else {
            builder
                .build_responder()
                .map_err(|e| anyhow::anyhow!("Failed to build Noise responder: {:?}", e))?
        };

        self.noise_state = Some(NoiseState::Handshake(Box::new(noise_state)));
        log::debug!("Noise handshake initialized with HKDF-derived PSK");

        Ok(())
    }

    /// Process a Noise handshake message
    /// Captures handshake hash when transitioning to transport mode
    #[allow(dead_code)]
    pub fn noise_handshake_step(&mut self, message: &[u8]) -> Result<Option<Vec<u8>>> {
        let state = self
            .noise_state
            .take()
            .ok_or_else(|| anyhow::anyhow!("Noise not initialized"))?;

        match state {
            NoiseState::Handshake(mut hs) => {
                let mut buf = vec![0u8; 65535];
                let len = hs
                    .read_message(message, &mut buf)
                    .context("Noise handshake read failed")?;
                buf.truncate(len);

                // Check if handshake is complete
                if hs.is_handshake_finished() {
                    log::debug!("Noise handshake complete, transitioning to transport mode");

                    // Capture handshake hash before transitioning
                    let handshake_hash = hs.get_handshake_hash().to_vec();
                    self.handshake_hash = Some(handshake_hash);
                    log::debug!("Captured handshake hash for SAS derivation");

                    let transport = hs.into_transport_mode()?;
                    self.noise_state = Some(NoiseState::Transport(Box::new(transport)));
                    Ok(if len > 0 { Some(buf) } else { None })
                } else {
                    self.noise_state = Some(NoiseState::Handshake(hs));
                    Ok(if len > 0 { Some(buf) } else { None })
                }
            }
            NoiseState::Transport(_) => {
                anyhow::bail!("Handshake already complete")
            }
        }
    }

    /// Write a Noise handshake message
    /// Captures handshake hash when transitioning to transport mode
    #[allow(dead_code)]
    pub fn noise_handshake_write(&mut self) -> Result<Vec<u8>> {
        let state = self
            .noise_state
            .take()
            .ok_or_else(|| anyhow::anyhow!("Noise not initialized"))?;

        match state {
            NoiseState::Handshake(mut hs) => {
                let mut buf = vec![0u8; 65535];
                let len = hs
                    .write_message(&[], &mut buf)
                    .context("Noise handshake write failed")?;
                buf.truncate(len);

                // Check if handshake is complete
                if hs.is_handshake_finished() {
                    log::debug!(
                        "Noise handshake complete (after write), transitioning to transport mode"
                    );

                    // Capture handshake hash before transitioning
                    let handshake_hash = hs.get_handshake_hash().to_vec();
                    self.handshake_hash = Some(handshake_hash);
                    log::debug!("Captured handshake hash for SAS derivation");

                    let transport = hs.into_transport_mode()?;
                    self.noise_state = Some(NoiseState::Transport(Box::new(transport)));
                } else {
                    self.noise_state = Some(NoiseState::Handshake(hs));
                }

                Ok(buf)
            }
            NoiseState::Transport(ts) => {
                // Put state back before bailing
                self.noise_state = Some(NoiseState::Transport(ts));
                anyhow::bail!("Handshake already complete")
            }
        }
    }

    /// Encrypt a message using Noise transport
    /// TODO: Use for send() message encryption
    #[allow(dead_code)]
    pub fn encrypt(&mut self, plaintext: &[u8]) -> Result<Vec<u8>> {
        let state = self
            .noise_state
            .as_mut()
            .ok_or_else(|| anyhow::anyhow!("Noise not initialized"))?;

        match state {
            NoiseState::Transport(ts) => {
                let mut buf = vec![0u8; 65535];
                let len = ts
                    .write_message(plaintext, &mut buf)
                    .context("Noise encryption failed")?;
                buf.truncate(len);
                Ok(buf)
            }
            NoiseState::Handshake(_) => {
                anyhow::bail!("Handshake not complete")
            }
        }
    }

    /// Decrypt a message using Noise transport
    /// TODO: Use for recv() message decryption
    #[allow(dead_code)]
    pub fn decrypt(&mut self, ciphertext: &[u8]) -> Result<Vec<u8>> {
        let state = self
            .noise_state
            .as_mut()
            .ok_or_else(|| anyhow::anyhow!("Noise not initialized"))?;

        match state {
            NoiseState::Transport(ts) => {
                let mut buf = vec![0u8; 65535];
                let len = ts
                    .read_message(ciphertext, &mut buf)
                    .context("Noise decryption failed")?;
                buf.truncate(len);
                Ok(buf)
            }
            NoiseState::Handshake(_) => {
                anyhow::bail!("Handshake not complete")
            }
        }
    }

    /// Generate SAS (Short Authentication String) for user verification
    /// If Noise handshake is complete, derives SAS from handshake hash (55 bits entropy)
    /// Otherwise falls back to session_id + invite_code for backwards compatibility
    pub fn generate_sas(&self, session_id: &str) -> String {
        // Prefer handshake hash if available (after Noise handshake completion)
        if let Some(ref handshake_hash) = self.handshake_hash {
            log::debug!("Deriving SAS from Noise handshake hash");
            return derive_sas_from_transcript(handshake_hash);
        }

        // Fallback: derive from session_id and invite_code
        // This is used before handshake completes or in legacy scenarios
        log::debug!("Deriving SAS from session_id (handshake not complete)");
        let mut hasher = Sha256::new();
        hasher.update(session_id.as_bytes());
        hasher.update(self.invite_code.as_bytes());
        let hash = hasher.finalize();

        // Use same word extraction logic as derive_sas_from_transcript
        derive_sas_from_transcript(&hash)
    }

    /// Generate numeric SAS (6 digits)
    /// TODO: Use in session initialization
    #[allow(dead_code)]
    pub fn generate_sas_numeric(&self, session_id: &str) -> String {
        let mut hasher = Sha256::new();
        hasher.update(session_id.as_bytes());
        hasher.update(self.invite_code.as_bytes());
        let hash = hasher.finalize();

        // Take first 4 bytes and convert to 6-digit number
        let num = u32::from_be_bytes([hash[0], hash[1], hash[2], hash[3]]) % 1_000_000;
        format!("{:06}", num)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_crypto_session_creation() {
        let session = CryptoSession::new("test-invite-code");
        assert!(session.is_ok());
    }

    #[test]
    fn test_sas_generation() {
        let session = CryptoSession::new("test-invite-code").unwrap();
        let sas = session.generate_sas("test-session-id");
        assert!(!sas.is_empty());
        // Should be formatted as word1-word2-word3-word4-word5
        assert!(sas.contains('-'));
    }

    #[test]
    fn test_sas_numeric_generation() {
        let session = CryptoSession::new("test-invite-code").unwrap();
        let sas_numeric = session.generate_sas_numeric("test-session-id");
        assert_eq!(sas_numeric.len(), 6);
        // Should be all digits
        assert!(sas_numeric.chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn test_sas_consistency() {
        let session = CryptoSession::new("test-invite-code").unwrap();
        let sas1 = session.generate_sas_numeric("test-session-id");
        let sas2 = session.generate_sas_numeric("test-session-id");
        // Same session_id and invite_code should produce same SAS
        assert_eq!(sas1, sas2);
    }

    #[test]
    fn test_spake2_exchange_two_party() {
        // Create two sessions with same password
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        // Both sides start and generate outbound messages
        let init_msg = initiator.spake2_start(true).unwrap();
        assert!(!init_msg.is_empty());

        let resp_msg = responder.spake2_start(false).unwrap();
        assert!(!resp_msg.is_empty());

        // Both sides complete exchange with peer's message
        let init_secret = initiator.spake2_finish(true, &resp_msg).unwrap();
        assert!(initiator.shared_secret.is_some());

        let resp_secret = responder.spake2_finish(false, &init_msg).unwrap();
        assert!(responder.shared_secret.is_some());

        // Both should derive the same secret
        assert_eq!(init_secret, resp_secret);
        assert!(!init_secret.is_empty());
    }

    #[test]
    fn test_noise_init_without_spake2() {
        let mut session = CryptoSession::new("test-invite-code").unwrap();
        // Should fail if SPAKE2 not performed first
        let result = session.init_noise(true);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("SPAKE2"));
    }

    #[test]
    fn test_noise_init_with_spake2() {
        // Two-party SPAKE2 exchange first
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        let init_msg = initiator.spake2_start(true).unwrap();
        let resp_msg = responder.spake2_start(false).unwrap();

        initiator.spake2_finish(true, &resp_msg).unwrap();
        responder.spake2_finish(false, &init_msg).unwrap();

        // Now test Noise initialization
        let result = initiator.init_noise(true);
        assert!(result.is_ok());
    }

    #[test]
    fn test_noise_handshake_flow() {
        // Create two sessions and complete SPAKE2 first
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        // Perform SPAKE2 exchange
        let init_msg = initiator.spake2_start(true).unwrap();
        let resp_msg = responder.spake2_start(false).unwrap();
        initiator.spake2_finish(true, &resp_msg).unwrap();
        responder.spake2_finish(false, &init_msg).unwrap();

        // Initialize Noise
        initiator.init_noise(true).unwrap();
        responder.init_noise(false).unwrap();

        // Initiator writes first message
        let msg1 = initiator.noise_handshake_write().unwrap();
        assert!(!msg1.is_empty());

        // Responder reads and responds
        let _response1 = responder.noise_handshake_step(&msg1).unwrap();

        // Continue handshake until complete
        // This is a simplified test - full handshake may require more messages
    }

    #[test]
    fn test_encrypt_without_handshake() {
        // Two-party SPAKE2 exchange first
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        let _init_msg = initiator.spake2_start(true).unwrap();
        let resp_msg = responder.spake2_start(false).unwrap();
        initiator.spake2_finish(true, &resp_msg).unwrap();

        initiator.init_noise(true).unwrap();

        // Should fail if handshake not complete
        let result = initiator.encrypt(b"test data");
        assert!(result.is_err());
    }

    #[test]
    fn test_decrypt_without_handshake() {
        // Two-party SPAKE2 exchange first
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        let _init_msg = initiator.spake2_start(true).unwrap();
        let resp_msg = responder.spake2_start(false).unwrap();
        initiator.spake2_finish(true, &resp_msg).unwrap();

        initiator.init_noise(true).unwrap();

        // Should fail if handshake not complete
        let result = initiator.decrypt(b"test data");
        assert!(result.is_err());
    }

    #[test]
    fn test_spake2_different_passwords() {
        let mut session1 = CryptoSession::new("password1").unwrap();
        let mut session2 = CryptoSession::new("password2").unwrap();

        // Just test that we can generate messages with different passwords
        let msg1 = session1.spake2_start(true).unwrap();
        let msg2 = session2.spake2_start(false).unwrap();

        // In production, finishing with different passwords would fail
        // But we can at least verify messages are generated
        assert!(!msg1.is_empty());
        assert!(!msg2.is_empty());
    }

    #[test]
    fn test_noise_state_transitions() {
        // Two-party SPAKE2 exchange first
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        // Initially no noise state
        assert!(initiator.noise_state.is_none());

        // Complete SPAKE2
        let _init_msg = initiator.spake2_start(true).unwrap();
        let resp_msg = responder.spake2_start(false).unwrap();
        initiator.spake2_finish(true, &resp_msg).unwrap();

        // After SPAKE2 and init, should have handshake state
        initiator.init_noise(true).unwrap();
        assert!(initiator.noise_state.is_some());

        // State should be Handshake
        if let Some(NoiseState::Handshake(_)) = &initiator.noise_state {
            // Correct
        } else {
            panic!("Expected Handshake state");
        }
    }

    #[test]
    fn test_multiple_spake2_exchanges() {
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();

        // First exchange
        let msg1 = initiator.spake2_start(true).unwrap();
        assert!(!msg1.is_empty());

        // Second exchange (generates new message)
        let msg2 = initiator.spake2_start(true).unwrap();
        assert!(!msg2.is_empty());

        // Messages should be different (different ephemeral keys)
        // But both valid
    }

    #[test]
    fn test_spake2_direct_without_wrapper() {
        // Test SPAKE2 directly without our wrapper to verify it works
        let password = Password::new(b"test-invite-code");

        // Initiator side (A)
        let (s_init, init_msg) = Spake2::<Ed25519Group>::start_a(
            &password,
            &Identity::new(b"client"), // idA
            &Identity::new(b"server"), // idB
        );

        // Responder side (B) - must use same identities in same order!
        let (s_resp, resp_msg) = Spake2::<Ed25519Group>::start_b(
            &password,
            &Identity::new(b"client"), // idA - same as start_a
            &Identity::new(b"server"), // idB - same as start_a
        );

        // Complete exchange
        let init_secret = s_init.finish(&resp_msg).unwrap();
        let resp_secret = s_resp.finish(&init_msg).unwrap();

        // Should match
        assert_eq!(init_secret, resp_secret);
    }

    #[test]
    fn test_hkdf_derivation_deterministic() {
        // Same input should produce same output
        let secret = b"test-shared-secret-32-bytes!!!!!";
        let psk1 = derive_noise_psk(secret).unwrap();
        let psk2 = derive_noise_psk(secret).unwrap();

        assert_eq!(psk1, psk2);
        assert_eq!(psk1.len(), 32); // 32 bytes for Noise PSK
    }

    #[test]
    fn test_hkdf_derivation_different_inputs() {
        // Different inputs should produce different outputs
        let secret1 = b"test-secret-1-32-bytes!!!!!!!!!!!";
        let secret2 = b"test-secret-2-32-bytes!!!!!!!!!!!";

        let psk1 = derive_noise_psk(secret1).unwrap();
        let psk2 = derive_noise_psk(secret2).unwrap();

        assert_ne!(psk1, psk2);
    }

    #[test]
    fn test_hkdf_derivation_output_length() {
        // Verify output is always 32 bytes regardless of input length
        let short_secret = b"short";
        let long_secret = b"this-is-a-much-longer-secret-string-for-testing-hkdf-derivation";

        let psk1 = derive_noise_psk(short_secret).unwrap();
        let psk2 = derive_noise_psk(long_secret).unwrap();

        assert_eq!(psk1.len(), 32);
        assert_eq!(psk2.len(), 32);
    }

    #[test]
    fn test_noise_init_with_hkdf() {
        // Verify that Noise initialization works with HKDF-derived PSK
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        // Perform SPAKE2 exchange
        let init_msg = initiator.spake2_start(true).unwrap();
        let resp_msg = responder.spake2_start(false).unwrap();
        initiator.spake2_finish(true, &resp_msg).unwrap();
        responder.spake2_finish(false, &init_msg).unwrap();

        // Initialize Noise (now uses HKDF internally)
        let result_init = initiator.init_noise(true);
        let result_resp = responder.init_noise(false);

        assert!(result_init.is_ok());
        assert!(result_resp.is_ok());
    }

    #[test]
    fn test_sas_from_handshake_hash_consistency() {
        // Test that both parties derive the same SAS after completing Noise handshake
        let mut initiator = CryptoSession::new("test-invite-code").unwrap();
        let mut responder = CryptoSession::new("test-invite-code").unwrap();

        // Complete SPAKE2 exchange
        let init_msg = initiator.spake2_start(true).unwrap();
        let resp_msg = responder.spake2_start(false).unwrap();
        initiator.spake2_finish(true, &resp_msg).unwrap();
        responder.spake2_finish(false, &init_msg).unwrap();

        // Initialize Noise
        initiator.init_noise(true).unwrap();
        responder.init_noise(false).unwrap();

        // Complete Noise handshake
        let msg1 = initiator.noise_handshake_write().unwrap();
        responder.noise_handshake_step(&msg1).unwrap();
        let msg2 = responder.noise_handshake_write().unwrap();
        initiator.noise_handshake_step(&msg2).unwrap();

        // Both should have handshake hash now
        assert!(initiator.handshake_hash.is_some());
        assert!(responder.handshake_hash.is_some());

        // Both should derive the SAME SAS from handshake hash
        let init_sas = initiator.generate_sas("session-id");
        let resp_sas = responder.generate_sas("session-id");

        assert_eq!(
            init_sas, resp_sas,
            "SAS should match after handshake completion"
        );

        // SAS should be 5 words separated by dashes
        let word_count = init_sas.split('-').count();
        assert_eq!(word_count, 5, "SAS should have 5 words");

        // All words should be from EFF wordlist (non-empty, lowercase)
        for word in init_sas.split('-') {
            assert!(!word.is_empty());
            assert!(word.chars().all(|c| c.is_ascii_lowercase()));
        }
    }

    #[test]
    fn test_sas_word_derivation() {
        // Test that derive_sas_from_transcript produces valid output
        let test_hash = b"test handshake hash for SAS generation";
        let sas = derive_sas_from_transcript(test_hash);

        // Should have 5 words
        let words: Vec<&str> = sas.split('-').collect();
        assert_eq!(words.len(), 5);

        // All words should be from the wordlist
        for word in &words {
            assert!(
                EFF_WORDLIST.contains(word),
                "Word '{}' not in wordlist",
                word
            );
        }

        // Same input should produce same output (deterministic)
        let sas2 = derive_sas_from_transcript(test_hash);
        assert_eq!(sas, sas2);
    }

    #[test]
    fn test_sas_different_hashes_different_sas() {
        // Different handshake hashes should produce different SAS
        let hash1 = b"handshake hash 1";
        let hash2 = b"handshake hash 2";

        let sas1 = derive_sas_from_transcript(hash1);
        let sas2 = derive_sas_from_transcript(hash2);

        assert_ne!(sas1, sas2, "Different hashes should produce different SAS");
    }

    #[test]
    fn test_sas_fallback_before_handshake() {
        // Test that SAS generation works before handshake completion
        let session = CryptoSession::new("test-invite-code").unwrap();

        // No handshake hash yet
        assert!(session.handshake_hash.is_none());

        // Should still generate SAS using fallback method
        let sas = session.generate_sas("test-session-id");

        assert!(!sas.is_empty());
        assert_eq!(sas.split('-').count(), 5);
    }
}
