// SPDX-License-Identifier: Apache-2.0
#include <flatbuffers/flatbuffers.h>
#include <vector>
#include <string>
#include <stdexcept>
#include "proof_generated.h"          // Generated by: flatc --cpp proof.fbs
#include "validation_generated.h" // Generated by: flatc --cpp validation.fbs
#include "blockheader_generated.h" // Generated by: flatc --cpp blockheader.fbs
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>

namespace py = pybind11;
using namespace proof;

// Helper: hex‑encode a FlatBuffers byte‑vector
static std::string bytes_to_hex(const flatbuffers::Vector<uint8_t>* vec) {
    if (!vec) return "";
    auto len = vec->size();
    std::string s;
    s.reserve(len * 2);
    static const char* hex_digits = "0123456789abcdef";
    for (size_t i = 0; i < len; ++i) {
        uint8_t byte = vec->Get(i);
        s.push_back(hex_digits[byte >> 4]);
        s.push_back(hex_digits[byte & 0x0F]);
    }
    return s;
}

py::dict unpack_proof(py::bytes buf) {
    // 1) Get root pointer
    auto sv = buf.cast<std::string_view>();

    // +++ begin FlatBuffers verification +++
   const uint8_t* data = reinterpret_cast<const uint8_t*>(sv.data());
   size_t        size = sv.size();
   flatbuffers::Verifier verifier(data, size);
   if (!proof::VerifyProofBuffer(verifier)) {
     throw std::runtime_error("FlatBuffer verification failed for Proof");
   }
   // +++ end FlatBuffers verification +++

    auto pf = flatbuffers::GetRoot<proof::Proof>(
        reinterpret_cast<const uint8_t*>(sv.data()));

    py::dict out;

    // 2) Scalars
    out["version"]            = pf->version();
    out["tick"]               = pf->tick();
    out["timestamp"]          = pf->timestamp();
    out["is_solution"]        = pf->is_solution();
    out["temperature"]        = pf->temperature();
    out["top_p"]              = pf->top_p();
    out["top_k"]              = pf->top_k();
    out["repetition_penalty"] = pf->repetition_penalty();

    // 3) Byte‑vectors → hex strings
    out["target"]        = bytes_to_hex(pf->target());
    out["vdf"]           = bytes_to_hex(pf->vdf());
    out["hash"]          = bytes_to_hex(pf->hash());
    out["block_hash"]    = bytes_to_hex(pf->block_hash());
    out["header_prefix"] = bytes_to_hex(pf->header_prefix());

    // 4) Strings
    out["model_identifier"]   = pf->model_identifier()
                               ? std::string(pf->model_identifier()->c_str(), pf->model_identifier()->size())
                               : std::string();
    out["compute_precision"]  = pf->compute_precision()
                               ? std::string(pf->compute_precision()->c_str(), pf->compute_precision()->size())
                               : std::string();
    out["ipfs_cid"]           = pf->ipfs_cid()
                               ? std::string(pf->ipfs_cid()->c_str(), pf->ipfs_cid()->size())
                               : std::string();
    out["extra_flags"]        = pf->extra_flags()
                               ? std::string(pf->extra_flags()->c_str(), pf->extra_flags()->size())
                               : std::string();

    // 5) 1D vectors → Python lists
    auto copy_uint_vec = [&](const flatbuffers::Vector<uint32_t>* vec){
      py::list L;
      if (vec) {
        for (size_t i = 0; i < vec->size(); ++i)
          L.append(vec->Get(i));
      }
      return L;
    };
    auto copy_float_vec = [&](const flatbuffers::Vector<float>* vec){
      py::list L;
      if (vec) {
        for (size_t i = 0; i < vec->size(); ++i)
          L.append(vec->Get(i));
      }
      return L;
    };
    auto copy_byte_vec = [&](const flatbuffers::Vector<uint8_t>* vec){
      py::list L;
      if (vec) {
        for (size_t i = 0; i < vec->size(); ++i)
          L.append(vec->Get(i));
      }
      return L;
    };

    out["chosen_tokens"]       = copy_uint_vec( pf->chosen_tokens() );
    out["chosen_probs"]        = copy_float_vec( pf->chosen_probs() );
    out["sampling_u"]          = copy_float_vec( pf->sampling_u() );
    out["softmax_normalizers"] = copy_float_vec( pf->softmax_normalizers() );
    out["prompt_tokens"]       = copy_uint_vec( pf->prompt_tokens() );
    out["pad_mask"]            = copy_byte_vec( pf->pad_mask() );

    // 6) 2D float tensors → numpy array
    auto make_2d_float = [&](const flatbuffers::Vector<flatbuffers::Offset<proof::FloatArray>>* outer){
      if (!outer) 
        return py::array_t<float>();  // default-constructed → empty

      size_t R = outer->size();
      size_t C = (R > 0 && (*outer)[0] && (*outer)[0]->values())
                 ? (*outer)[0]->values()->size()
                 : 0;

      py::array_t<float> arr({ (ssize_t)R, (ssize_t)C });
      auto info = arr.request();
      float* data = static_cast<float*>(info.ptr);

      for (size_t i = 0; i < R; ++i) {
        auto inner = (*outer)[i]->values();
        for (size_t j = 0; j < C; ++j) {
          data[i*C + j] = inner ? inner->Get(j) : 0.0f;
        }
      }
      return arr;
    };

    // 7) 2D uint tensors → numpy array
    auto make_2d_uint = [&](const flatbuffers::Vector<flatbuffers::Offset<proof::UIntArray>>* outer){
      if (!outer)
        return py::array_t<uint32_t>(); // default-constructed → empty

      size_t R = outer->size();
      size_t C = (R > 0 && (*outer)[0] && (*outer)[0]->values())
                 ? (*outer)[0]->values()->size()
                 : 0;

      py::array_t<uint32_t> arr({ (ssize_t)R, (ssize_t)C });
      auto info = arr.request();
      uint32_t* data = static_cast<uint32_t*>(info.ptr);

      for (size_t i = 0; i < R; ++i) {
        auto inner = (*outer)[i]->values();
        for (size_t j = 0; j < C; ++j) {
          data[i*C + j] = inner ? inner->Get(j) : 0u;
        }
      }
      return arr;
    };

    out["topk_logits"]     = make_2d_float( pf->topk_logits() );
    out["logsumexp_stats"] = make_2d_float( pf->logsumexp_stats() );
    out["topk_indices"]    = make_2d_uint( pf->topk_indices() );

    return out;
}

static py::dict unpack_proof_obj(const proof::Proof *pf) {
  py::dict out;

  // 2) Scalars
  out["version"]            = pf->version();
  out["tick"]               = pf->tick();
  out["timestamp"]          = pf->timestamp();
  out["is_solution"]        = pf->is_solution();
  out["temperature"]        = pf->temperature();
  out["top_p"]              = pf->top_p();
  out["top_k"]              = pf->top_k();
  out["repetition_penalty"] = pf->repetition_penalty();

  // 3) Byte‑vectors → hex strings
  out["target"]        = bytes_to_hex(pf->target());
  out["vdf"]           = bytes_to_hex(pf->vdf());
  out["hash"]          = bytes_to_hex(pf->hash());
  out["block_hash"]    = bytes_to_hex(pf->block_hash());
  out["header_prefix"] = bytes_to_hex(pf->header_prefix());

  // 4) Strings
  out["model_identifier"]   = pf->model_identifier()
                              ? std::string(pf->model_identifier()->c_str(), pf->model_identifier()->size())
                              : std::string();
  out["compute_precision"]  = pf->compute_precision()
                              ? std::string(pf->compute_precision()->c_str(), pf->compute_precision()->size())
                              : std::string();

  // 5) 1D vectors → Python lists
  auto copy_uint_vec = [&](const flatbuffers::Vector<uint32_t>* vec){
    py::list L;
    if (vec) {
      for (size_t i = 0; i < vec->size(); ++i)
        L.append(vec->Get(i));
    }
    return L;
  };
  auto copy_float_vec = [&](const flatbuffers::Vector<float>* vec){
    py::list L;
    if (vec) {
      for (size_t i = 0; i < vec->size(); ++i)
        L.append(vec->Get(i));
    }
    return L;
  };
  auto copy_byte_vec = [&](const flatbuffers::Vector<uint8_t>* vec){
    py::list L;
    if (vec) {
      for (size_t i = 0; i < vec->size(); ++i)
        L.append(vec->Get(i));
    }
    return L;
  };

  out["chosen_tokens"]       = copy_uint_vec( pf->chosen_tokens() );
  out["chosen_probs"]        = copy_float_vec( pf->chosen_probs() );
  out["sampling_u"]          = copy_float_vec( pf->sampling_u() );
  out["softmax_normalizers"] = copy_float_vec( pf->softmax_normalizers() );
  out["prompt_tokens"]       = copy_uint_vec( pf->prompt_tokens() );
  out["pad_mask"]            = copy_byte_vec( pf->pad_mask() );

  // 6) 2D float tensors → numpy array
  auto make_2d_float = [&](const flatbuffers::Vector<flatbuffers::Offset<proof::FloatArray>>* outer){
    if (!outer) 
      return py::array_t<float>();  // default-constructed → empty

    size_t R = outer->size();
    size_t C = (R > 0 && (*outer)[0] && (*outer)[0]->values())
                ? (*outer)[0]->values()->size()
                : 0;

    py::array_t<float> arr({ (ssize_t)R, (ssize_t)C });
    auto info = arr.request();
    float* data = static_cast<float*>(info.ptr);

    for (size_t i = 0; i < R; ++i) {
      auto inner = (*outer)[i]->values();
      for (size_t j = 0; j < C; ++j) {
        data[i*C + j] = inner ? inner->Get(j) : 0.0f;
      }
    }
    return arr;
  };

  // 7) 2D uint tensors → numpy array
  auto make_2d_uint = [&](const flatbuffers::Vector<flatbuffers::Offset<proof::UIntArray>>* outer){
    if (!outer)
      return py::array_t<uint32_t>(); // default-constructed → empty

    size_t R = outer->size();
    size_t C = (R > 0 && (*outer)[0] && (*outer)[0]->values())
                ? (*outer)[0]->values()->size()
                : 0;

    py::array_t<uint32_t> arr({ (ssize_t)R, (ssize_t)C });
    auto info = arr.request();
    uint32_t* data = static_cast<uint32_t*>(info.ptr);

    for (size_t i = 0; i < R; ++i) {
      auto inner = (*outer)[i]->values();
      for (size_t j = 0; j < C; ++j) {
        data[i*C + j] = inner ? inner->Get(j) : 0u;
      }
    }
    return arr;
  };

  out["topk_logits"]     = make_2d_float( pf->topk_logits() );
  out["logsumexp_stats"] = make_2d_float( pf->logsumexp_stats() );
  out["topk_indices"]    = make_2d_uint( pf->topk_indices() );
  
  return out;
}

// Unpack a ValidationRequest buffer into Python dict, including nested Proof
py::dict unpack_validation_request(py::bytes buf) {
    auto sv   = buf.cast<std::string_view>();
    const uint8_t* base = reinterpret_cast<const uint8_t*>(sv.data());
    size_t         size = sv.size();

    // +++ Full‑buffer validation +++
    flatbuffers::Verifier verifier(base, size);
    if (!proof::VerifyValidationRequestBuffer(verifier)) {
      throw std::runtime_error("FlatBuffer verification failed for ValidationRequest");
    }
    // +++ end validation +++

    // Safe to parse root now
    auto req = flatbuffers::GetRoot<ValidationRequest>(base);
    py::dict out;

    // Common fields
    auto h = req->hash_id();
    out["hash_id"]         = py::bytes(reinterpret_cast<const char*>(h->data()), h->size());
    out["validation_type"] = int(req->validation_type());
    out["request_type"]    = int(req->request_type());

    // Branch on union
    switch (req->request_type()) {
      case ValidationUnion_BlockValidation: {
        auto blk = req->request_as_BlockValidation();
        py::dict d;
        d["version"]       = blk->version();
        d["timestamp"]     = blk->timestamp();
        d["bits"]          = blk->bits();
        d["nonce"]         = blk->nonce();
        d["adjusted_bits"] = blk->adjusted_bits();
        // Registered model difficulty (appended v3 field; 0 = not provided —
        // old senders). Lets the verifier derive the admission target (§6).
        d["difficulty"]    = blk->difficulty();
        // raw bytes
        auto ph = blk->prev_block_hash();
        d["prev_block_hash"] = py::bytes(reinterpret_cast<const char*>(ph->data()), ph->size());

        // Unpack nested Proof safely
        const proof::Proof *pf_ptr = blk->pow_blob();
        if (!verifier.VerifyTable(pf_ptr)) {
          throw std::runtime_error("Nested Proof table verification failed");
        }
        d["pow_blob"] = unpack_proof_obj(pf_ptr);

        out["request"] = d;
        break;
      }
      case ValidationUnion_ModelValidation: {
        auto mdl = req->request_as_ModelValidation();
        py::dict d;
        d["model_name"]   = mdl->model_name()->str();
        d["model_commit"] = mdl->model_commit()->str();
        d["difficulty"]   = mdl->difficulty();
        d["cid"]          = mdl->cid()->str();
        d["extra"]        = mdl->extra()->str();
        auto tx = mdl->txid();
        d["txid"]         = py::bytes(reinterpret_cast<const char*>(tx->data()), tx->size());
        auto bh = mdl->block_hash();
        d["block_hash"]   = py::bytes(reinterpret_cast<const char*>(bh->data()), bh->size());
        d["block_height"] = mdl->block_height();
        out["request"]    = d;
        break;
      }
      default:
        throw std::runtime_error("Unknown ValidationUnion type");
    }

    return out;
}

// Unpack a MiningResponse buffer into Python dict
py::dict unpack_mining_response(py::bytes buf) {
    auto sv   = buf.cast<std::string_view>();
    const uint8_t* base = reinterpret_cast<const uint8_t*>(sv.data());
    size_t         size = sv.size();

    // Since MiningResponse is not a root type, we'll parse it without buffer verification
    // or verify it as a generic flatbuffer
    auto mr = flatbuffers::GetRoot<proof::MiningResponse>(base);
    
    // Verify the table structure
    flatbuffers::Verifier verifier(base, size);
    if (!verifier.VerifyTable(mr)) {
      throw std::runtime_error("FlatBuffer verification failed for MiningResponse");
    }
    py::dict out;

    // Extract basic fields
    out["req_id"]       = mr->req_id();
    out["nonce"]        = mr->nonce();
    out["adjusted_bits"] = mr->adjusted_bits();
    out["difficulty"]   = mr->difficulty();
    
    // Extract completion_id if present
    auto cid = mr->completion_id();
    out["completion_id"] = cid ? std::string(cid->c_str(), cid->size()) : std::string();

    // Extract pow_blob_hash as hex string
    out["pow_blob_hash"] = bytes_to_hex(mr->pow_blob_hash());

    // Unpack nested Proof if present
    const proof::Proof *pf_ptr = mr->pow_blob();
    if (pf_ptr && verifier.VerifyTable(pf_ptr)) {
        out["pow_blob"] = unpack_proof_obj(pf_ptr);
    } else {
        out["pow_blob"] = py::none();
    }

    return out;
}

// Helper: Convert hex string to bytes
static std::vector<uint8_t> hex_to_bytes(const std::string& hex) {
    std::vector<uint8_t> bytes;
    for (size_t i = 0; i < hex.length(); i += 2) {
        std::string byteString = hex.substr(i, 2);
        uint8_t byte = (uint8_t) strtol(byteString.c_str(), NULL, 16);
        bytes.push_back(byte);
    }
    return bytes;
}

// Internal helper to pack Proof from dict into builder
static flatbuffers::Offset<proof::Proof> pack_proof_internal(flatbuffers::FlatBufferBuilder& builder, py::dict data) {
    // pfunpack is a DUMB packer (TIP-0003 boundary): the v3
    // admission nonce is carried inside extra_flags (merged by the shared
    // helper at the writer layer, extracted by the verifier from extra_flags).
    // pack_proof_internal serializes the extra_flags string verbatim (below)
    // and preserves it across a repack. A SIDE "admission_nonce" field would
    // be a second, silent v3 writer path — this packer would ignore it and
    // emit a proof missing the nonce. Fail loudly rather than invent one.
    if (data.contains("admission_nonce")) {
        throw std::invalid_argument(
            "pfunpack.pack_proof does not accept a side 'admission_nonce'; "
            "merge it into extra_flags via the shared v3 helper "
            "(pow_v3.merge_extra_flags_v3) at the writer layer before packing");
    }
    // Extract scalar fields
    uint32_t version = data["version"].cast<uint32_t>();
    uint64_t tick = data["tick"].cast<uint64_t>();
    uint64_t timestamp = data["timestamp"].cast<uint64_t>();
    bool is_solution = data["is_solution"].cast<bool>();
    float temperature = data["temperature"].cast<float>();
    float top_p = data["top_p"].cast<float>();
    uint32_t top_k = data["top_k"].cast<uint32_t>();
    float repetition_penalty = data["repetition_penalty"].cast<float>();

    // Extract byte vectors (hex strings -> bytes)
    auto target_hex = data["target"].cast<std::string>();
    auto target_bytes = hex_to_bytes(target_hex);
    auto target_vec = builder.CreateVector(target_bytes);

    auto vdf_hex = data["vdf"].cast<std::string>();
    auto vdf_bytes = hex_to_bytes(vdf_hex);
    auto vdf_vec = builder.CreateVector(vdf_bytes);

    auto hash_hex = data["hash"].cast<std::string>();
    auto hash_bytes = hex_to_bytes(hash_hex);
    auto hash_vec = builder.CreateVector(hash_bytes);

    auto block_hash_hex = data["block_hash"].cast<std::string>();
    auto block_hash_bytes = hex_to_bytes(block_hash_hex);
    auto block_hash_vec = builder.CreateVector(block_hash_bytes);

    auto header_prefix_hex = data["header_prefix"].cast<std::string>();
    auto header_prefix_bytes = hex_to_bytes(header_prefix_hex);
    auto header_prefix_vec = builder.CreateVector(header_prefix_bytes);

    // Extract string fields
    auto model_id = builder.CreateString(data["model_identifier"].cast<std::string>());
    auto compute_prec = builder.CreateString(data["compute_precision"].cast<std::string>());
    auto ipfs_cid = builder.CreateString(data.contains("ipfs_cid") ? 
        data["ipfs_cid"].cast<std::string>() : "");
    auto extra_flags = builder.CreateString(data.contains("extra_flags") ? 
        data["extra_flags"].cast<std::string>() : "");

    // Extract 1D arrays
    std::vector<uint32_t> chosen_tokens;
    if (data.contains("chosen_tokens")) {
        for (auto item : data["chosen_tokens"]) {
            chosen_tokens.push_back(py::cast<uint32_t>(item));
        }
    }
    auto chosen_tokens_vec = builder.CreateVector(chosen_tokens);

    std::vector<float> chosen_probs;
    if (data.contains("chosen_probs")) {
        for (auto item : data["chosen_probs"]) {
            chosen_probs.push_back(py::cast<float>(item));
        }
    }
    auto chosen_probs_vec = builder.CreateVector(chosen_probs);

    std::vector<float> sampling_u;
    if (data.contains("sampling_u")) {
        for (auto item : data["sampling_u"]) {
            sampling_u.push_back(py::cast<float>(item));
        }
    }
    auto sampling_u_vec = builder.CreateVector(sampling_u);

    std::vector<float> softmax_normalizers;
    if (data.contains("softmax_normalizers")) {
        for (auto item : data["softmax_normalizers"]) {
            softmax_normalizers.push_back(py::cast<float>(item));
        }
    }
    auto softmax_norm_vec = builder.CreateVector(softmax_normalizers);

    std::vector<uint32_t> prompt_tokens;
    if (data.contains("prompt_tokens")) {
        for (auto item : data["prompt_tokens"]) {
            prompt_tokens.push_back(py::cast<uint32_t>(item));
        }
    }
    auto prompt_tokens_vec = builder.CreateVector(prompt_tokens);

    std::vector<uint8_t> pad_mask;
    if (data.contains("pad_mask")) {
        for (auto item : data["pad_mask"]) {
            pad_mask.push_back(py::cast<uint8_t>(item));
        }
    }
    auto pad_mask_vec = builder.CreateVector(pad_mask);

    // Extract 2D arrays (topk_logits, topk_indices, logsumexp_stats)
    std::vector<flatbuffers::Offset<FloatArray>> topk_logits_vec;
    if (data.contains("topk_logits")) {
        for (auto row : data["topk_logits"]) {
            std::vector<float> row_data;
            for (auto val : row) {
                row_data.push_back(py::cast<float>(val));
            }
            auto row_vec = builder.CreateVector(row_data);
            auto float_array = CreateFloatArray(builder, row_vec);
            topk_logits_vec.push_back(float_array);
        }
    }
    auto topk_logits_final = builder.CreateVector(topk_logits_vec);

    std::vector<flatbuffers::Offset<UIntArray>> topk_indices_vec;
    if (data.contains("topk_indices")) {
        for (auto row : data["topk_indices"]) {
            std::vector<uint32_t> row_data;
            for (auto val : row) {
                row_data.push_back(py::cast<uint32_t>(val));
            }
            auto row_vec = builder.CreateVector(row_data);
            auto uint_array = CreateUIntArray(builder, row_vec);
            topk_indices_vec.push_back(uint_array);
        }
    }
    auto topk_indices_final = builder.CreateVector(topk_indices_vec);

    std::vector<flatbuffers::Offset<FloatArray>> logsumexp_stats_vec;
    if (data.contains("logsumexp_stats")) {
        for (auto row : data["logsumexp_stats"]) {
            std::vector<float> row_data;
            for (auto val : row) {
                row_data.push_back(py::cast<float>(val));
            }
            auto row_vec = builder.CreateVector(row_data);
            auto float_array = CreateFloatArray(builder, row_vec);
            logsumexp_stats_vec.push_back(float_array);
        }
    }
    auto logsumexp_final = builder.CreateVector(logsumexp_stats_vec);

    // Create the Proof (argument order must match schema)
    // Schema order (proof.fbs):
    // version, tick, timestamp,
    // target, vdf, hash, block_hash, header_prefix,
    // is_solution, model_identifier, compute_precision, ipfs_cid, extra_flags,
    // temperature, top_p, top_k, repetition_penalty,
    // chosen_tokens, chosen_probs, sampling_u, softmax_normalizers,
    // prompt_tokens, pad_mask,
    // topk_logits, topk_indices, logsumexp_stats
    auto proof_off = CreateProof(builder,
        version,
        tick,
        timestamp,
        target_vec,
        vdf_vec,
        hash_vec,
        block_hash_vec,
        header_prefix_vec,
        is_solution,
        model_id,
        compute_prec,
        ipfs_cid,
        extra_flags,
        temperature,
        top_p,
        top_k,
        repetition_penalty,
        chosen_tokens_vec,
        chosen_probs_vec,
        sampling_u_vec,
        softmax_norm_vec,
        prompt_tokens_vec,
        pad_mask_vec,
        topk_logits_final,
        topk_indices_final,
        logsumexp_final);
    return proof_off;
}

// Helper to unpack Proof table into dict (internal use)
static py::dict unpack_proof_internal(const proof::Proof* pf) {
    py::dict out;
    out["version"]            = pf->version();
    out["tick"]               = pf->tick();
    out["timestamp"]          = pf->timestamp();
    out["is_solution"]        = pf->is_solution();
    out["temperature"]        = pf->temperature();
    out["top_p"]              = pf->top_p();
    out["top_k"]              = pf->top_k();
    out["repetition_penalty"] = pf->repetition_penalty();
    out["target"]        = bytes_to_hex(pf->target());
    out["vdf"]           = bytes_to_hex(pf->vdf());
    out["hash"]          = bytes_to_hex(pf->hash());
    out["block_hash"]    = bytes_to_hex(pf->block_hash());
    out["header_prefix"] = bytes_to_hex(pf->header_prefix());
    out["model_identifier"]   = pf->model_identifier() ? pf->model_identifier()->str() : std::string();
    out["compute_precision"]  = pf->compute_precision() ? pf->compute_precision()->str() : std::string();
    out["ipfs_cid"]           = pf->ipfs_cid() ? pf->ipfs_cid()->str() : std::string();
    out["extra_flags"]        = pf->extra_flags() ? pf->extra_flags()->str() : std::string();
    return out;
}

// Pack a Proof from Python dict to FlatBuffer bytes
py::bytes pack_proof(py::dict data) {
    flatbuffers::FlatBufferBuilder builder(1024);
    auto proof_off = pack_proof_internal(builder, data);
    builder.Finish(proof_off, "PROF");
    return py::bytes(reinterpret_cast<const char*>(builder.GetBufferPointer()), builder.GetSize());
}

PYBIND11_MODULE(pfunpack, m) {
    m.doc() = "FlatBuffers Proof pack/unpack helpers";

    m.def("unpack_proof", &unpack_proof, "Unpack a Proof FlatBuffer to dict");
    m.def("unpack_validation_request", &unpack_validation_request, "Unpack ValidationRequest incl. nested Proof");
    m.def("unpack_mining_response", &unpack_mining_response, "Unpack MiningResponse incl. nested Proof");
    m.def("pack_proof", &pack_proof, "Pack a Proof from a dictionary");

    // Pack a ValidationRequest from a dictionary
    m.def("pack_validation_request", [](py::dict data) -> py::bytes {
        flatbuffers::FlatBufferBuilder builder(1024);

        // Required fields
        std::vector<uint8_t> hash_id;
        if (data.contains("hash_id")) {
            auto hid = data["hash_id"].cast<std::string>();
            hash_id.assign(hid.begin(), hid.end());
        }
        auto hash_id_vec = builder.CreateVector(hash_id);

        uint8_t validation_type = data.contains("validation_type") ? data["validation_type"].cast<uint8_t>() : 0;

        // Union: currently only BlockValidation and ModelValidation are supported here
        proof::ValidationUnion req_type = proof::ValidationUnion_NONE;
        flatbuffers::Offset<void> req_offset;

        if (data.contains("request") && py::isinstance<py::dict>(data["request"])) {
            py::dict req = data["request"].cast<py::dict>();
            std::string kind = req.contains("kind") ? req["kind"].cast<std::string>() : std::string();
            if (kind == "BlockValidation") {
                // Fields
                uint32_t version = req.contains("version") ? req["version"].cast<uint32_t>() : 0;
                uint32_t timestamp = req.contains("timestamp") ? req["timestamp"].cast<uint32_t>() : 0;
                uint32_t bits = req.contains("bits") ? req["bits"].cast<uint32_t>() : 0;
                uint32_t nonce = req.contains("nonce") ? req["nonce"].cast<uint32_t>() : 0;
                uint32_t adjusted_bits = req.contains("adjusted_bits") ? req["adjusted_bits"].cast<uint32_t>() : 0;
                // Registered model difficulty (v3 admission target derivation,
                // TIP-0003); 0 = not provided.
                int64_t blk_difficulty = req.contains("difficulty") ? req["difficulty"].cast<int64_t>() : 0;

                auto prev_block_hash = req.contains("prev_block_hash") ? req["prev_block_hash"].cast<std::string>() : std::string();
                auto prev_block_hash_vec = builder.CreateVector(reinterpret_cast<const uint8_t*>(prev_block_hash.data()), prev_block_hash.size());

                flatbuffers::Offset<proof::Proof> proof_offset = 0;
                if (req.contains("pow_blob") && py::isinstance<py::dict>(req["pow_blob"])) {
                    proof_offset = pack_proof_internal(builder, req["pow_blob"].cast<py::dict>());
                }

                proof::BlockValidationBuilder bvb(builder);
                bvb.add_version(version);
                bvb.add_timestamp(timestamp);
                bvb.add_bits(bits);
                bvb.add_nonce(nonce);
                bvb.add_adjusted_bits(adjusted_bits);
                if (blk_difficulty != 0) bvb.add_difficulty(blk_difficulty);
                bvb.add_prev_block_hash(prev_block_hash_vec);
                if (proof_offset.o != 0) bvb.add_pow_blob(proof_offset);
                auto blk = bvb.Finish();
                req_type = proof::ValidationUnion_BlockValidation;
                req_offset = blk.Union();
            } else if (kind == "ModelValidation") {
                auto model_name = builder.CreateString(req.contains("model_name") ? req["model_name"].cast<std::string>() : "");
                auto model_commit = builder.CreateString(req.contains("model_commit") ? req["model_commit"].cast<std::string>() : "");
                int64_t difficulty = req.contains("difficulty") ? req["difficulty"].cast<int64_t>() : 0;
                auto cid = builder.CreateString(req.contains("cid") ? req["cid"].cast<std::string>() : "");
                auto extra = builder.CreateString(req.contains("extra") ? req["extra"].cast<std::string>() : "");
                std::string txid = req.contains("txid") ? req["txid"].cast<std::string>() : std::string();
                auto txid_vec = builder.CreateVector(reinterpret_cast<const uint8_t*>(txid.data()), txid.size());
                std::string block_hash = req.contains("block_hash") ? req["block_hash"].cast<std::string>() : std::string();
                auto block_hash_vec = builder.CreateVector(reinterpret_cast<const uint8_t*>(block_hash.data()), block_hash.size());
                int32_t block_height = req.contains("block_height") ? req["block_height"].cast<int32_t>() : 0;

                proof::ModelValidationBuilder mvb(builder);
                mvb.add_model_name(model_name);
                mvb.add_model_commit(model_commit);
                mvb.add_difficulty(difficulty);
                mvb.add_cid(cid);
                mvb.add_extra(extra);
                mvb.add_txid(txid_vec);
                mvb.add_block_hash(block_hash_vec);
                mvb.add_block_height(block_height);
                auto mdl = mvb.Finish();
                req_type = proof::ValidationUnion_ModelValidation;
                req_offset = mdl.Union();
            }
        }

        proof::ValidationRequestBuilder vrb(builder);
        vrb.add_hash_id(hash_id_vec);
        vrb.add_validation_type(static_cast<proof::ValidationType>(validation_type));
        if (req_type != proof::ValidationUnion_NONE) {
            vrb.add_request_type(req_type);
            vrb.add_request(req_offset);
        }
        auto root = vrb.Finish();
        builder.Finish(root);
        return py::bytes(reinterpret_cast<const char*>(builder.GetBufferPointer()), builder.GetSize());
    }, "Pack a validation request from a dictionary", py::arg("data"));

    // Pack a MiningResponse from a dictionary
    m.def("pack_mining_response", [](py::dict data) -> py::bytes {
        flatbuffers::FlatBufferBuilder builder(1024);

        // Create pow_blob (Proof) if provided
        flatbuffers::Offset<proof::Proof> proof_offset = 0;
        if (data.contains("pow_blob") && py::isinstance<py::dict>(data["pow_blob"])) {
            proof_offset = pack_proof_internal(builder, data["pow_blob"].cast<py::dict>());
        }

        // pow_blob_hash: allow passing hex string or raw bytes
        std::vector<uint8_t> pow_blob_hash;
        if (data.contains("pow_blob_hash")) {
            if (py::isinstance<py::bytes>(data["pow_blob_hash"])) {
                std::string hash_str = data["pow_blob_hash"].cast<std::string>();
                pow_blob_hash.assign(hash_str.begin(), hash_str.end());
            } else {
                std::string hash_hex = data["pow_blob_hash"].cast<std::string>();
                pow_blob_hash = hex_to_bytes(hash_hex);
            }
        }
        auto pow_blob_hash_offset = builder.CreateVector(pow_blob_hash);

        // Create completion_id string
        flatbuffers::Offset<flatbuffers::String> completion_id_offset = 0;
        if (data.contains("completion_id")) {
            std::string completion_id = data["completion_id"].cast<std::string>();
            completion_id_offset = builder.CreateString(completion_id);
        }

        // Create MiningResponse
        proof::MiningResponseBuilder mr_builder(builder);

        if (data.contains("req_id"))
            mr_builder.add_req_id(data["req_id"].cast<uint32_t>());
        if (data.contains("nonce"))
            mr_builder.add_nonce(data["nonce"].cast<uint32_t>());
        if (data.contains("adjusted_bits"))
            mr_builder.add_adjusted_bits(data["adjusted_bits"].cast<uint32_t>());

        mr_builder.add_pow_blob_hash(pow_blob_hash_offset);

        if (data.contains("difficulty"))
            mr_builder.add_difficulty(data["difficulty"].cast<uint32_t>());

        if (proof_offset.o != 0)
            mr_builder.add_pow_blob(proof_offset);

        if (completion_id_offset.o != 0)
            mr_builder.add_completion_id(completion_id_offset);

        auto mining_response = mr_builder.Finish();

        // Note: MiningResponse doesn't have a file identifier in the schema
        // The root type for blockheader.fbs is BlockHeader, not MiningResponse
        builder.Finish(mining_response);

        return py::bytes(reinterpret_cast<const char*>(builder.GetBufferPointer()), 
                        builder.GetSize());
    }, "Pack a mining response from a dictionary", py::arg("data"));

    m.def("pack_mining_response_with_proof_bytes", [](
        uint32_t req_id,
        uint32_t nonce,
        uint32_t adjusted_bits,
        py::bytes pow_blob_hash,
        uint32_t difficulty,
        py::bytes proof_bytes,
        const std::string& completion_id = ""
    ) -> py::bytes {
        // This is the most efficient version - accepts already-serialized Proof bytes
        // and directly builds MiningResponse without dictionary overhead

        std::string proof_str(proof_bytes);

        // Verify the proof bytes have PROF identifier
        if (proof_str.size() < 8 || 
            proof_str[4] != 'P' || proof_str[5] != 'R' || 
            proof_str[6] != 'O' || proof_str[7] != 'F') {
            throw std::runtime_error("Invalid proof bytes - missing PROF identifier");
        }

        // Extract the Proof table from the bytes
        const uint8_t* proof_buf = reinterpret_cast<const uint8_t*>(proof_str.data());
        auto proof_verifier = flatbuffers::Verifier(proof_buf, proof_str.size());
        if (!proof::VerifyProofBuffer(proof_verifier)) {
            throw std::runtime_error("Invalid Proof FlatBuffer");
        }

        const proof::Proof* proof_table = proof::GetProof(proof_buf);

        // Now create a new builder for MiningResponse
        flatbuffers::FlatBufferBuilder builder(1024);

        // We need to copy the Proof table into our new builder
        flatbuffers::Offset<proof::Proof> proof_offset = 0;

        // For now, we'll deserialize and re-serialize (not ideal but safe)
        py::dict proof_dict = unpack_proof_internal(proof_table);
        proof_offset = pack_proof_internal(builder, proof_dict);

        // Create pow_blob_hash vector
        std::string hash_str(pow_blob_hash);
        auto pow_blob_hash_offset = builder.CreateVector(
            reinterpret_cast<const uint8_t*>(hash_str.data()), 
            hash_str.size()
        );

        // Create completion_id string
        flatbuffers::Offset<flatbuffers::String> completion_id_offset = 0;
        if (!completion_id.empty()) {
            completion_id_offset = builder.CreateString(completion_id);
        }

        // Create MiningResponse
        proof::MiningResponseBuilder mr_builder(builder);
        mr_builder.add_req_id(req_id);
        mr_builder.add_nonce(nonce);
        mr_builder.add_adjusted_bits(adjusted_bits);
        mr_builder.add_pow_blob_hash(pow_blob_hash_offset);
        mr_builder.add_difficulty(difficulty);
        mr_builder.add_pow_blob(proof_offset);

        if (completion_id_offset.o != 0)
            mr_builder.add_completion_id(completion_id_offset);

        auto mining_response = mr_builder.Finish();
        builder.Finish(mining_response);

        return py::bytes(reinterpret_cast<const char*>(builder.GetBufferPointer()), 
                        builder.GetSize());
    }, "Pack a mining response with pre-serialized proof bytes (most efficient)",
       py::arg("req_id"),
       py::arg("nonce"),
       py::arg("adjusted_bits"),
       py::arg("pow_blob_hash"),
       py::arg("difficulty"),
       py::arg("proof_bytes"),
       py::arg("completion_id") = ""
    );
}
