// SPDX-License-Identifier: Apache-2.0
/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package kyc-prover/cgo */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bridge.go"

#include <stdlib.h>
#include <string.h>

// Generic result structure for any Groth16 proof
typedef struct {
    unsigned char* proof_data;      // Raw proof bytes (gnark serialization)
    int proof_len;
    unsigned char* public_inputs;   // Raw public input bytes (32 bytes per field element)
    int public_inputs_len;
    char* error_msg;                // Error message (NULL if success)
} Groth16ProofResult;

// Result structure for MiMC hash computation
typedef struct {
    unsigned char* hash_data;       // 32-byte hash result
    int hash_len;
    char* error_msg;                // Error message (NULL if success)
} MiMCHashResult;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern Groth16ProofResult Groth16_ProveKYC(char* pkPath, char* vkPath, char* requestJSON);
extern Groth16ProofResult Groth16_ProveKYCHD(char* pkPath, char* vkPath, char* requestJSON);
extern Groth16ProofResult Groth16_ProveKYCHDV1(char* pkPath, char* vkPath, char* requestJSON);
extern char* Groth16_Verify(char* vkPath, unsigned char* proofData, int proofLen, unsigned char* publicInputs, int publicInputsLen);
extern void Groth16_FreeResult(Groth16ProofResult* result);
extern MiMCHashResult Groth16_ComputeMiMCHash(char* tag, char* input1Hex, char* input2Hex, char* input3Hex);
extern void Groth16_FreeMiMCResult(MiMCHashResult* result);

#ifdef __cplusplus
}
#endif
