// Copyright (c) 2026 The TensorCash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit/.

//! Cleartext relay envelope (minimal) for cosign session frames.
//!
//! Every frame on the relay/transport now carries `handshake_id`, `sender`,
//! and `kind` so the recv path can drop:
//!
//! * frames from a previous handshake of the same room (different hid),
//! * own frames echoed back by the relay (matching hid + kind but
//!   `sender == self.instance_id`),
//! * wrong-phase frames (kind=Handshake during transport phase, or
//!   kind=Data before handshake completes).
//!
//! The payload bytes (`ct`) are the same opaque blob the caller produced —
//! this layer never inspects them. The envelope is intentionally tiny so
//! a follow-up can extend it (role, seq for replay prevention, etc.)
//! without re-doing the send/recv plumbing.

use base64::{engine::general_purpose, Engine as _};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FrameKind {
    /// SPAKE2 / Noise handshake bytes pre-transport-mode.
    #[serde(rename = "hs")]
    Handshake,
    /// Noise transport-mode ciphertext.
    #[serde(rename = "data")]
    Data,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayEnvelope {
    /// Per-handshake nonce (random 128-bit hex). Generated by the initiator
    /// in `cosign.init`, conveyed to the responder via `invite_link`, written
    /// on every frame, and checked on every recv.
    pub hid: String,
    /// Per-side instance id (random 128-bit hex). Each side generates its
    /// own at session creation. recv() drops frames whose `sender` matches
    /// the local instance id — that filters own messages echoed back by
    /// relays that broadcast to every client in the room (including the
    /// sender). Without this, an own SPAKE2/Noise/transport frame returns
    /// from the relay, passes the hid + kind check, and is fed into the
    /// peer's cipher state — exactly the failure mode the envelope is
    /// supposed to prevent.
    pub sender: String,
    /// Frame phase. recv() expects `Data` after `Session::handshake_complete`;
    /// stray `Handshake` frames (own bytes echoed by relays, late peer
    /// retries) are dropped.
    pub kind: FrameKind,
    /// Opaque ciphertext / handshake-bytes payload, base64-encoded on the
    /// wire so the envelope is plain JSON.
    #[serde(with = "b64_bytes")]
    pub ct: Vec<u8>,
}

impl RelayEnvelope {
    pub fn new(
        hid: impl Into<String>,
        sender: impl Into<String>,
        kind: FrameKind,
        ct: Vec<u8>,
    ) -> Self {
        Self {
            hid: hid.into(),
            sender: sender.into(),
            kind,
            ct,
        }
    }

    /// Serialise to JSON bytes for the wire.
    pub fn to_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(self)
    }

    /// Parse from JSON bytes. Returns `Err` if the bytes aren't a well-formed
    /// envelope — callers should treat that as "drop the frame and keep
    /// reading" so peers running older bridges (no envelope) don't poison
    /// a Noise cipher state mid-flight.
    pub fn parse(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes)
    }
}

mod b64_bytes {
    use super::*;
    use serde::{de::Error, Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(bytes: &[u8], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&general_purpose::STANDARD.encode(bytes))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        general_purpose::STANDARD.decode(s).map_err(Error::custom)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_handshake_frame() {
        let env = RelayEnvelope::new(
            "deadbeef",
            "self-id",
            FrameKind::Handshake,
            b"\x01\x02\x03".to_vec(),
        );
        let bytes = env.to_bytes().expect("serialise");
        let parsed = RelayEnvelope::parse(&bytes).expect("parse");
        assert_eq!(parsed.hid, "deadbeef");
        assert_eq!(parsed.sender, "self-id");
        assert_eq!(parsed.kind, FrameKind::Handshake);
        assert_eq!(parsed.ct, b"\x01\x02\x03");
    }

    #[test]
    fn roundtrip_data_frame() {
        let env = RelayEnvelope::new("abc123", "instance-A", FrameKind::Data, vec![0xff; 64]);
        let bytes = env.to_bytes().unwrap();
        let parsed = RelayEnvelope::parse(&bytes).unwrap();
        assert_eq!(parsed.hid, "abc123");
        assert_eq!(parsed.sender, "instance-A");
        assert_eq!(parsed.kind, FrameKind::Data);
        assert_eq!(parsed.ct.len(), 64);
        assert!(parsed.ct.iter().all(|&b| b == 0xff));
    }

    #[test]
    fn rejects_garbage() {
        assert!(RelayEnvelope::parse(b"not json").is_err());
        assert!(RelayEnvelope::parse(b"{}").is_err());
        // Missing ct field
        assert!(RelayEnvelope::parse(br#"{"hid":"x","sender":"a","kind":"data"}"#).is_err());
        // Missing sender field (envelope without sender from old code must be
        // rejected — otherwise own echoes silently pass the filter).
        assert!(RelayEnvelope::parse(br#"{"hid":"x","kind":"data","ct":"aGk="}"#).is_err());
    }

    #[test]
    fn wire_format_is_json() {
        let env = RelayEnvelope::new("x", "src", FrameKind::Handshake, b"hi".to_vec());
        let bytes = env.to_bytes().unwrap();
        let s = std::str::from_utf8(&bytes).expect("utf8");
        assert!(s.contains("\"hid\":\"x\""));
        assert!(s.contains("\"sender\":\"src\""));
        assert!(s.contains("\"kind\":\"hs\""));
        assert!(s.contains("\"ct\":\"aGk=\""));  // base64("hi")
    }
}
