#!/usr/bin/env python3
"""Transcribe tests/vectors/v3_vectors.json into a generated C++ header for
tests/test_pow_v3_cpp.cpp (TIP-0003 cross-language vectors).

Run from shared-utils/pow-utils (or anywhere — paths are script-relative):
    python tests/gen_v3_vectors_header.py
writes tests/vectors/v3_vectors_embedded.h. Pure transcription: this script
never recomputes a value, so the JSON written by gen_v3_vectors.py stays the
single source of truth. Doubles are emitted as C++17 hexfloat literals
(float.hex()) so the embedded values are bit-exact.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
IN_PATH = os.path.join(HERE, "vectors", "v3_vectors.json")
OUT_PATH = os.path.join(HERE, "vectors", "v3_vectors_embedded.h")


def cxx_str(s):
    if s is None:
        return "nullptr"
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 0x20:
            out.append("\\%03o" % ord(ch))  # 3-digit octal: never greedy
        else:
            out.append(ch)
    return '"%s"' % "".join(out)


def cxx_double(x):
    return float(x).hex()  # valid C++17 hexfloat literal, bit-exact


def emit_i64_array(name, values):
    body = ",".join(str(int(v)) for v in values)
    return f"static const int64_t {name}[] = {{{body}}};\n"


def emit_double_array(name, values):
    body = ",".join(cxx_double(v) for v in values)
    return f"static const double {name}[] = {{{body}}};\n"


def main():
    with open(IN_PATH) as f:
        vectors = json.load(f)

    lines = []
    lines.append("// GENERATED by tests/gen_v3_vectors_header.py from "
                 "tests/vectors/v3_vectors.json — DO NOT EDIT.\n")
    lines.append("// Golden cross-language vectors for pow_v3 "
                 "(TIP-0003).\n")
    lines.append("#pragma once\n")
    lines.append("#include <cstdint>\n")
    lines.append("#include <cstddef>\n\n")
    lines.append("namespace v3_vectors {\n\n")

    consts = vectors["constants"]
    lines.append(f"constexpr size_t POW_WINDOW_SIZE = {consts['pow_window_size']};\n")
    lines.append(f"constexpr uint64_t B_FLOOR_BITS = {consts['b_floor_bits']};\n")
    lines.append(f"constexpr uint64_t B_FREE_BITS = {consts['b_free_bits']};\n")
    lines.append(f"constexpr uint64_t BCRED_R = {consts['bcred_r']};\n")
    lines.append(f"constexpr uint64_t BCRED_N_MAX = {consts['bcred_n_max']};\n")
    lines.append(f"constexpr const char* BCRED_TABLE_SHA256 = "
                 f"{cxx_str(consts['bcred_table_sha256'])};\n")
    lines.append(f"constexpr uint64_t ATOL_Q63_CEIL = {consts['atol_q63_ceil']}ULL;\n")
    lines.append(f"constexpr double ATOL = {cxx_double(consts['atol'])};\n")
    lines.append(f"constexpr size_t EXTRA_FLAGS_MAX_BYTES = {consts['extra_flags_max_bytes']};\n")
    lines.append(f"constexpr int EXTRA_FLAGS_MAX_DEPTH = {consts['extra_flags_max_depth']};\n\n")

    # ---- step_hash ------------------------------------------------------- #
    lines.append("struct StepHashVector {\n"
                 "    const char* name;\n"
                 "    const char* header_prefix_hex;\n"
                 "    const char* vdf_hex;\n"
                 "    uint32_t tick;\n"
                 "    uint32_t step;\n"
                 "    const int64_t* context_tokens;\n"
                 "    size_t context_len;\n"
                 "    const char* precision;\n"
                 "    const char* admission_nonce_hex;  // nullptr = no nonce\n"
                 "    size_t message_len;\n"
                 "    const char* message_sha256_hex;\n"
                 "    double u_double;\n"
                 "};\n\n")
    for i, v in enumerate(vectors["step_hash"]):
        lines.append(emit_i64_array(f"kStepCtx{i}", v["context_tokens"]))
    lines.append("\nstatic const StepHashVector kStepHash[] = {\n")
    for i, v in enumerate(vectors["step_hash"]):
        lines.append(
            "    {%s, %s, %s, %dU, %dU, kStepCtx%d, %d, %s, %s, %d, %s, %s},\n"
            % (cxx_str(v["name"]), cxx_str(v["header_prefix"]),
               cxx_str(v["vdf"]), v["tick"], v["step"], i,
               len(v["context_tokens"]), cxx_str(v["precision"]),
               cxx_str(v["admission_nonce"]), v["message_len"],
               cxx_str(v["message_sha256"]), cxx_double(v["u_double"])))
    lines.append("};\n")
    lines.append("constexpr size_t kStepHashCount = "
                 "sizeof(kStepHash) / sizeof(kStepHash[0]);\n\n")

    # ---- admission -------------------------------------------------------- #
    # msg_w is rebuilt by the test from the step_hash vector whose (no-nonce)
    # message sha256 equals window_first_step_message_sha256_hex. The full
    # prefix (prompt_tokens + pad_mask) feeds pow_v3::prompt_commitment; the
    # expected commitment is pinned separately from the final Argon digest.
    for i, v in enumerate(vectors["admission"]):
        toks = v["prompt_tokens"]
        mask = v["pad_mask"]
        if toks:
            lines.append("static const int64_t kAdmissionPrompt%d[] = {%s};\n"
                         % (i, ", ".join(str(int(t)) for t in toks)))
        if mask:
            lines.append("static const uint8_t kAdmissionMask%d[] = {%s};\n"
                         % (i, ", ".join("1" if b else "0" for b in mask)))
    lines.append("\nstruct AdmissionVector {\n"
                 "    const char* name;\n"
                 "    const char* window_first_step_message_sha256_hex;\n"
                 "    const char* model_identifier;\n"
                 "    const char* admission_nonce_hex;\n"
                 "    const int64_t* prompt_tokens;   // nullptr when empty\n"
                 "    size_t prompt_tokens_count;\n"
                 "    const uint8_t* pad_mask;        // nullptr when empty\n"
                 "    size_t pad_mask_count;\n"
                 "    const char* prompt_commitment_hex;\n"
                 "    size_t admission_message_len;\n"
                 "    const char* argon2id_digest_hex;\n"
                 "};\n\n")
    lines.append("static const AdmissionVector kAdmission[] = {\n")
    for i, v in enumerate(vectors["admission"]):
        toks = v["prompt_tokens"]
        mask = v["pad_mask"]
        lines.append("    {%s, %s, %s, %s, %s, %d, %s, %d, %s, %d, %s},\n" % (
            cxx_str(v["name"]),
            cxx_str(v["window_first_step_message_sha256"]),
            cxx_str(v["model_identifier"]), cxx_str(v["admission_nonce"]),
            ("kAdmissionPrompt%d" % i) if toks else "nullptr", len(toks),
            ("kAdmissionMask%d" % i) if mask else "nullptr", len(mask),
            cxx_str(v["prompt_commitment"]),
            v["admission_message_len"], cxx_str(v["argon2id_digest"])))
    lines.append("};\n")
    lines.append("constexpr size_t kAdmissionCount = "
                 "sizeof(kAdmission) / sizeof(kAdmission[0]);\n\n")

    # ---- target_derivation ------------------------------------------------ #
    lines.append("struct TargetVector {\n"
                 "    int64_t difficulty;\n"
                 "    uint64_t normalizer;\n"
                 "    uint64_t decode_us_at_normalizer;\n"
                 "    uint64_t elig_alpha_num;\n"
                 "    uint64_t elig_alpha_den;\n"
                 "    uint64_t argon_ref_us;\n"
                 "    uint64_t expected_tries;\n"
                 "    const char* admission_target_hex_be;\n"
                 "};\n\n")
    lines.append("static const TargetVector kTargets[] = {\n")
    for v in vectors["target_derivation"]:
        lines.append(
            "    {%dLL, %dULL, %dULL, %dULL, %dULL, %dULL, %dULL, %s},\n"
            % (v["difficulty"], v["normalizer"], v["decode_us_at_normalizer"],
               v["elig_alpha"][0], v["elig_alpha"][1], v["argon_ref_us"],
               int(v["expected_tries"]), cxx_str(v["admission_target_hex_be"])))
    lines.append("};\n")
    lines.append("constexpr size_t kTargetCount = "
                 "sizeof(kTargets) / sizeof(kTargets[0]);\n\n")

    # ---- carrier (§3 extraction + parser bounds) --------------------------- #
    lines.append("struct CarrierVector {\n"
                 "    const char* name;\n"
                 "    const char* extra_flags;\n"
                 "    const char* admission_nonce_hex;  // nullptr = no nonce claimed\n"
                 "};\n\n")
    lines.append("static const CarrierVector kCarrier[] = {\n")
    for v in vectors["carrier"]:
        lines.append("    {%s, %s, %s},\n" % (
            cxx_str(v["name"]), cxx_str(v["extra_flags"]),
            cxx_str(v["admission_nonce"])))
    lines.append("};\n")
    lines.append("constexpr size_t kCarrierCount = "
                 "sizeof(kCarrier) / sizeof(kCarrier[0]);\n\n")

    # ---- b_cred ------------------------------------------------------------ #
    lines.append("struct BCredVector {\n"
                 "    const char* name;\n"
                 "    const double* lower;\n"
                 "    const double* upper;\n"
                 "    size_t len;\n"
                 "    double atol;\n"
                 "    uint64_t b_cred_units;\n"
                 "    const char* tier;\n"
                 "};\n\n")
    for i, v in enumerate(vectors["b_cred"]):
        lines.append(emit_double_array(f"kBCredLower{i}", v["lower"]))
        lines.append(emit_double_array(f"kBCredUpper{i}", v["upper"]))
    lines.append("\nstatic const BCredVector kBCred[] = {\n")
    for i, v in enumerate(vectors["b_cred"]):
        assert len(v["lower"]) == len(v["upper"])
        lines.append(
            "    {%s, kBCredLower%d, kBCredUpper%d, %d, %s, %dULL, %s},\n"
            % (cxx_str(v["name"]), i, i, len(v["lower"]),
               cxx_double(v["atol"]), int(v["b_cred_units"]), cxx_str(v["tier"])))
    lines.append("};\n")
    lines.append("constexpr size_t kBCredCount = "
                 "sizeof(kBCred) / sizeof(kBCred[0]);\n\n")

    lines.append("}  // namespace v3_vectors\n")

    with open(OUT_PATH, "w") as f:
        f.write("".join(lines))
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
