#!/usr/bin/env python3
"""Transcribe tests/vectors/soak_grinded_cases.json into a C++ header for
tests/soak_v3_cpp_check.cpp (offline-replay soak cross-check).

Run AFTER tests/soak_v3_offline_replay.py has written the JSON:
    python tests/gen_soak_cases_header.py
writes tests/vectors/soak_grinded_cases_embedded.h. Pure transcription — never
recomputes a value — so the Python-ground JSON stays the single source of truth.
The C++ side rebuilds each admission_message / argon2id_digest / admission_target
from these literals and asserts its verdict equals the embedded Python verdict on
the SAME really-ground nonces.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
IN_PATH = os.path.join(HERE, "vectors", "soak_grinded_cases.json")
OUT_PATH = os.path.join(HERE, "vectors", "soak_grinded_cases_embedded.h")


def cxx_str(s):
    if s is None:
        return "nullptr"
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 0x20:
            out.append("\\%03o" % ord(ch))
        else:
            out.append(ch)
    return '"%s"' % "".join(out)


def emit_bytes(name, hexstr):
    """Emit a uint8_t[] from a hex string (may be empty)."""
    b = bytes.fromhex(hexstr)
    body = ",".join(str(x) for x in b)
    return f"static const uint8_t {name}[] = {{{body}}};\n", len(b)


def main():
    with open(IN_PATH) as f:
        data = json.load(f)
    cases = data["cases"]

    lines = []
    lines.append("// GENERATED by tests/gen_soak_cases_header.py from "
                 "tests/vectors/soak_grinded_cases.json — DO NOT EDIT.\n")
    lines.append("// Really-ground v3 admission soak cases "
                 "(TIP-0003).\n")
    lines.append("#pragma once\n")
    lines.append("#include <cstdint>\n")
    lines.append("#include <cstddef>\n\n")
    lines.append("namespace soak_cases {\n\n")

    # Per-case byte arrays.
    for i, c in enumerate(cases):
        for field, arr in (("MsgW", c["msg_w"]),
                           ("Commit", c["prompt_commitment"]),
                           ("TargetLe", c["admission_target_le"]),
                           ("Nonce", c["admission_nonce"]),
                           ("Digest", c["digest"]),
                           ("TamperNonce", c["tamper_nonce"]),
                           ("TamperDigest", c["tamper_digest"])):
            text, _ = emit_bytes(f"k{field}{i}", arr)
            lines.append(text)
        lines.append("\n")

    lines.append("struct SoakCase {\n"
                 "    const char* name;\n"
                 "    int64_t difficulty;\n"
                 "    const uint8_t* msg_w;\n"
                 "    size_t msg_w_len;\n"
                 "    const char* model_identifier;\n"
                 "    const uint8_t* commitment;      // 32\n"
                 "    const uint8_t* target_le;       // 32\n"
                 "    const uint8_t* nonce;           // 32\n"
                 "    const uint8_t* digest;          // 32 (Python argon2id)\n"
                 "    bool real_valid;\n"
                 "    const uint8_t* tamper_nonce;    // 32\n"
                 "    const uint8_t* tamper_digest;   // 32 (Python argon2id)\n"
                 "    bool tamper_valid;\n"
                 "};\n\n")

    lines.append("static const SoakCase kSoak[] = {\n")
    for i, c in enumerate(cases):
        msg_w_len = len(bytes.fromhex(c["msg_w"]))
        lines.append(
            "    {%s, %dLL, kMsgW%d, %d, %s, kCommit%d, kTargetLe%d, "
            "kNonce%d, kDigest%d, %s, kTamperNonce%d, kTamperDigest%d, %s},\n"
            % (cxx_str(c["name"]), c["difficulty"], i, msg_w_len,
               cxx_str(c["model_identifier"]), i, i, i, i,
               "true" if c["real_valid"] else "false", i, i,
               "true" if c["tamper_valid"] else "false"))
    lines.append("};\n")
    lines.append("constexpr size_t kSoakCount = sizeof(kSoak) / sizeof(kSoak[0]);\n\n")
    lines.append("}  // namespace soak_cases\n")

    with open(OUT_PATH, "w") as f:
        f.write("".join(lines))
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
