# TensorCash Wallet — lightning config
# Zero Tor, zero chain history, max speed.
prune=550
dbcache=4096
proxy=
maxconnections=16
shrinkdebugfile=1
daemon=0
server=1
rpcallowip=127.0.0.1
listen=0
validationapi=desktop
useextapi=0
fallbackfee=0.00001

[tensor]
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
rpcport=39240
